### ISSUE TITLE
Bad MIPS detection

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#12]
Difference between GUI flags (FORMAT) and debug flags (FORMAT+MIPS). The MIPS error is falsely reported here, because the difference between the number of MIPS of vanilla and modded is simply due to a different resolution.
![28hhdbpf1es1](https://cloud.githubusercontent.com/assets/12874678/9047094/c1908226-3a2f-11e5-8632-336dd54c93b0.png)
Here are the images, fixed and unfixed : http://filebin.ca/28hiEG3E4waV/TestDDS.7z

**Comment by HeffU** [comment]
After looking at this it seems that what you're seeing is simply debug output, it will for example output the MIPS line regardless of current/expected, even if they match. So it's not as much a falsely reported error as that it's not an error at all in the view of the code, it just prints both format and mips always.

Looks like it has no problems handling the case where there are more mips than expected, so I'll close this for now, and we can return here if it turns out to be a problem anywhere.
