### ISSUE TITLE
Suggestion : Remove "Other Engines" menu

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#130]
It mostly confuses new users and the ME1 & ME2 versions of Sequence Editor, Package Editor, etc could be easily integrated in their ME3 counterpart, just like with Texplorer and TPF/DDS.

**Comment by SirCxyrtyx** [comment]
I think integrating those tools would be rather complex actually, but it's still probably a good idea. There's a lot of duplicated code between them right now. I believe the most important hurdle would be to standardize the public interface of the PCCObject classes. The ones for ME1 and ME2 should be brought in-line with the ME3 one.

**Comment by KFreon** [comment]
That merger took me quite some time and I did it the lazy way, as Sir is pointing out. 
If you want Sir, take a look at the WPFMerger branch. I've already merged a bunch of classes, made some interfaces, etc.
It's probably poor code as usual, but might be able to save you/me/someone some time.

**Comment by ghost** [comment]
I'm not sure about this integration as things stand right now. I haven't experienced any issues with it confusing users -- Package and Sequence Editors aren't User Tools, anyway, they are Developer Tools.  What experiences have you had, Creeper?

This division is something that was talked about as I worked on overhauling the menu organization. ME1, ME2, and ME3 have significantly different file structure and like Sir says above, there's quite a bit of work involved -- this is why these tools are still separate.

The key thing If we're going to integrate them -- make these particular tools cross-game -- is that they need to have the _same_ capabilities regardless of game. That's the only way it really makes sense. This is the case with Texplorer and TPF Tools. However, this is _not_ the case with the Package and Sequence Editors. Not at all.

Right now the ME3 versions of these two tools have totally different capabilities than the ME1/ME2 versions. PCCEd2 for ME3 is significantly more advanced. The ME2 sequence editor doesn't have any editing capabilities at all -- and there is no ME1 sequence editor. Merging tools for different games is going to get very, very confusing if only certain editing features are available for certain games... yet all the files open with the same tool. Currently, there's a clear distinction: you open an ME2 PCC in ME2Explorer, with the ME2 Package Editor and you have a certain set of editing capabilities. You open an ME3 PCC with ME3Explorer, in PCCEd2 and you have _those_ editing capabilities. This is logical.

Next, there's more than just the sequence and package editors to consider:
- ME1 has Save Game Editors. There is no equivalent tool for ME3. Removing the "Other Engines" option -- and thus "ME1Explorer" means we'd have to put this tool in the ME3Explorer User Tool main menu. This doesn't make sense, since _it's not for ME3._ This will indeed cause confusion, as folks assume everything accessible inside ME3Explorer modifies ME3, since, well... that's how it is!
- ME2 has a DLC Crack. Same as above, this doesn't exist for ME3. 
- UDK Explorer could probably be moved to the Developer Tools area, but there is also a Package Editor and Meshplorer for it, similar to ME2's Package/Sequence Editor combination. No idea what we do there.

I'd say once a tool is fully capable of all the same actions regardless of game platform, _then_ they should be merged, and removed from ME1/ME2Explorer. However, like I said, that still doesn't solve the issues with tools that are unique to ME1 and/or ME2. It makes no sense to move those tools into ME3Explorer, and not moving them means retaining the ME1/ME2Explorer division... which means retaining "Other Engines".

**Comment by Mgamerz** [comment]
Pretty sure the dlc crack was removed wasn't it? I saw references to it
removed. Probably a wise decision IMO

**Comment by starkgate** [comment]
I get your point. What was confusing people is the fact that "ME2Explorer" and "ME1Explorer" sound like the exact equivalent of "ME3Explorer", which they were originally supposed to be right ? The problem is, some users will expect eg TPF/DDS Tools for ME2 to be in ME2Explorer, they won't necessarily think of clicking the "Modding ME3" button.
Maybe it's just a problem with naming then, instead of "ME2Explorer", we could use "Additional Tools for ME2" or something.

In any case, it was just a suggestion, you're free to ignore it :).

**Comment by ghost** [comment]
@CreeperLava -- Sure, equivalent in the sense that the tools for each game are in each "ME#Explorer", but not in the sense that everything for ME3 is (or will be) replicated and available for ME1/ME2. 

I think a lot of this will be addressed once I write the TPF Tools article for the wiki, and make potential tweaks to the Texplorer and ModMaker articles. For example, I can make it clearer in the opening paragraphs that these tools are cross-game. I can explain that the tools were originally separate and then integrated in rev "X" and the ME3Exp tool is used regardless of game. If someone is confused and looks on the wiki (as they should be), they should easily locate this information.

Beyond the wiki, if there's actually an issue with users not seeing the "Modding ME#" at the top right of the tool window, there are additional tweaks that could be made to the relevant tools. For example, when clicking to open the tool from the main menu, it could immediately trigger a pop up that asks the user: "What game would you like to modify?" and provide buttons for ME1/2/3. This introduces the user to the mechanism before they enter the tool. The button inside the tool would remain, but this way the desired game is immediately selected.

"Additional Tools" as a new main menu option, leading to the ME1 Save Tools, ME2 DLC Crack, and UDK Explorer is definitely a possibility. Implementing this change makes the most sense once the Package and Sequence Editors become full cross game tools. However, we also have to think ahead. The _potential_ for new tools -- I'm guessing -- is why the ME1 and ME2Explorers were created in the first place. Sure, there aren't many tools for them now, but there's always a chance things will grow. Creating "Explorers" for those games, separate from ME3Explorer, ensured there was a place to put any new tools. Doing so also prevented complications with the code for the existing ME3 Tool, and omitted the chance of bugs borking it. It also allowed the coder flexibility since not all functionalities needed to be present immediately for the ME1/ME2 tool. Etc, etc.

**Comment by KFreon** [comment]
I don't mind the idea of changing the naming there. Dunno if it's necessary, but I can see where you're coming from.

**Comment by ghost** [comment]
@KFreon -- If we're not going to change this, let's close the issue so we can keep a good visual of what's left for the new stable :)

**Comment by KFreon** [comment]
Roger that.
