### ISSUE TITLE
ModMaker, Detect Other not working

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#139]
The new "Detect Other" feature that's meant to detect files in DLC mods isn't working. No duplicate file names are detected. No errors are reported. Debug Output:

![mm_detectother](https://cloud.githubusercontent.com/assets/13645804/12280178/d38fd5e0-b940-11e5-83dd-10314af0a44e.PNG)

Also, if this feature stays in, the menu option needs to be renamed "MESH ONLY: Detect other files" is misleading on two accounts:
1. MOD files can contain any export replacement, not just meshes. K, I know you equate MODs with meshes in your head, but this isn't the case. We don't want to give folks the impression MOD files can only be used for meshes.
2. "Detect other files" is pretty ambiguous. What files and where?

How about simply "Detect New DLC Files", instead?

**Comment by KFreon** [comment]
I'm tempted to completely remove this button as there's absolutely no support in behind for it atm.
Even if the detection worked, the script won't run it. It's going to take quite a bit more work on my part to get that running.

As for the name, I put that there because running this on a texture mod is not only unnecessary, but it WILL crash...
I guess I can filter out texture jobs.

**Comment by ghost** [comment]
I don't think you want to filter out texture jobs -- some MOD files can still contain them. Assuming that's relevant.

And, if you want to remove it before the stable, I'd say that's fine -- it's an experimental (but nice) feature.

**Comment by KFreon** [comment]
To clarify, I won't filter out the entire mod file, just the jobs detected as textures.

**Comment by KFreon** [comment]
Yeah I'm going to remove this button for now :(
I'll sort it out eventually.

**Comment by ghost** [comment]
Just confirming removal. (rev742)
