### ISSUE TITLE
rev731, ModMaker GUI, Scrolling gone, Bottom Menu Inaccessible

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#158]
I was attempting to verify the fix for #131, but have now found that I cannot extract any jobs, since no scroll bar or bottom menu appears when a .mod file is loaded:

![rev731_mmscrolling](https://cloud.githubusercontent.com/assets/13645804/12890253/bf934b10-ce37-11e5-9d18-041ff1245d0f.PNG)

Rev731 is in the background, and rev727 in the foreground. You can see both the missing scroll bars and bottom menu.

I'm guessing this has to do with your 4K issue in VS, K. There _must_ be some way to disable whatever VS is doing. Obviously VS can't assume that all users have 4K screens, lol.

FYI, I need to test several other issues with MM, but can't do that until this issue is rectified.

**Comment by starkgate** [comment]
See #149 too, this problem is also in TPF/DDS. One 'fix', if you need to get to the buttons, is to use tab multiple times to select the button, then hit enter to activate it. Of course you don't see if it is selected, but through trial and error I now know for example, that you can select the analyse button in TPF/DDS by hitting tab 11 times. Hopefully that helps until it gets fixed.

**Comment by ghost** [comment]
@CreeperLava -- TPF Tools GUI is actually fine for me. I have no issues seeing the bottom menu, the scroll bars, or the large buttons at the bottom. GUI is identical in r727 and r731. (I'm comparing these to each other since my last round of testing was for r727)

**Comment by starkgate** [comment]
Really ? That's peculiar... You're on W7 ? If not that may be one explanation.

**Comment by ghost** [comment]
@CreeperLava -- Yep, Win7 64bit. On a standard 1920x1080 screen.

**Comment by KFreon** [comment]
HRURHHFGUHGUHFKJAHNKJGHBKISAHGD
DPI in Winforms is abysmal unless I'm missing a magic setting somewhere.
I don't know what to do here guys, but there is one piece of info that might help figure some stuff out.

In Display Settings, are any of your monitors NOT 100% scale? Mine for example is 150% scale.

**Comment by starkgate** [comment]
Hmm, you're right, TPF/DDS does display correctly. I tried it on a computer at school. I suppose the fact that teamviewer adapts my windows resolution to my laptop's is part of it. This shouldn't happen anyways, but at least there seems to be a fix.
Here is what happens when I change the resolution slightly :
![capture](https://cloud.githubusercontent.com/assets/12874678/12918749/e503a638-cf40-11e5-854b-1354019d4828.PNG)

**Comment by ghost** [comment]
@KFreon -- Nope, my monitor is set at 100%.

Let's try tagging @HeffU and see if he knows how to fix it :)

**Comment by KFreon** [comment]
Looks like I might have fixed it...
Now I gotta rearrange all the things so they're visible. 
There's actually a little setting, hidden very well, that adapts things to different DPI's, but only most things, hence rearranging.

**Comment by ghost** [comment]
Verified fixed in r733.
