### ISSUE TITLE
ME3 .mods getting detected as ME1 .mods

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#16]
I downloaded some multiplayer .mods (texture replacing only) here : http://www.nexusmods.com/masseffect3/mods/77/
I tried to load the .mods directly in TPF/DDS. Whether I repair or not, TPF/DDS switches automatically to "Modding ME1" while loading. Which makes no sense (MP in ME1, really ?^^).
ModMaker also detects the .mod as a ME1 mod.

I initially didn't think of checking the Debug Output, but when I did, something very interesting came out : http://pastebin.ca/3087452 . The paths are clearly very wrong. A similar output is given for any of the .mods linked above.

**Comment by HeffU** [comment]
This was most peculiar, with a number of underlying issues:

Firstly, the ME3Directories would never report that any DLC files existed at all, this is now fixed.

Secondly, if no gamefiles was found that matches the .mod, modmaker would default to modding ME1, this is now fixed so that it aborts and the user gets a pop-up saying that the files cant be found. The pop-up suggests that the user check their path, and also makes sure they have DLC extracted.

Thirdly, and this is where I'm not sure what to do, all the mods on the page you linked have weird formatting of their files. Each DLC has the path DLC_FOLDER_NAME\PCC_FILE_NAME.pcc, rather than the DLC_FOLDER_NAME\CookedPCConsole\PCC_FILE_NAME.pcc.
Is this some kind of old paths from before the toolset did things properly, and should we in that case write some specialized conversion logic to update such old DLC mods? Or is it simply an error on the modders part, and the DLC part of this has never worked outside of his/her specific install?

Fixes for 1 and 2 are in: 573d8ed9360601234d2ba616aad47d27c1190e8d

**Comment by starkgate** [comment]
This must be on the mod's side, as the .pccs are extracted in the CookedPCConsole folder. Is there a way to edit the .mod to fix the paths ?

**Comment by HeffU** [comment]
Yeah, if you open the .mod without fixing it you should be able to select each item and update the paths, but it's a hell lot of manual work.

**Comment by ghost** [comment]
Yeah, this also sounds like the ,mod's problem. Something that autofix needs to address maybe,  Creeper?

**Comment by starkgate** [comment]
I don't think that's necessary. The mod isn't very downloaded anymore, so it would probably not be worth it to add a whole new autofix function for a single mod.

**Comment by HeffU** [comment]
As it only seems to affect this old mod, and it's quite a major thing to add for autofix, where any solution could possibly 'cause other problems, I'm gonna close this issue for now.

**Comment by HeffU** [comment]
I actually went ahead and added autocorrection for those legacy ME3Mods that has this old format.
It's nothing smart, simply checking if a ME3 DLC is referenced without the CookedPCConsole subfolder, see 73ca2e6ffcd2c272b1cf9c2a1e06a907324c1fcc.
