### ISSUE TITLE
rev731, TPF Tools Bulk Extract Doesn't Work

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#162]
As far as I can tell, this doesn't work at all. At least if I'm understanding the description, of what it's supposed to do:

"Added. Extracts a folder of TPFs to separate folders."

I assume this means if I load 2+ TPFs in TPF Tools that this new Bulk Extract function will extract the DDSes associated with each TPF into a separate subfolder, placed in the folder of the user's choosing.

I've tried this, and a bit similar to ModMaker's PCC Compare, nothing at all happens. Nothing is extracted and no error.

**Comment by starkgate** [comment]
That's not how it works, it extracts the TPFs from the folder you choose to separate subfolders. Maybe a better description would help ? I tried it out, it definitely worked.

**Comment by ghost** [comment]
Ah, okay. Well, in that case, it partially works.

I got this error for one of the TPFs it tried to extract:

![tpfbulkextract_index](https://cloud.githubusercontent.com/assets/13645804/12898650/b60a138c-ce62-11e5-9ca1-cfb37382d239.PNG)

Seems like it's throwing the error during the Ash face TPF or when trying to extract the Blue Suns TPF; I can't tell. I haven't used any of these yet so I can't say if there's anything wrong with the DDSes, but seems like that shouldn't be relevant to extraction.

**Comment by starkgate** [comment]
Yeah, I had similar problems with a few select TPFs that refused to be extracted this way. If you extract them individually though, it works. Index out of range shouldn't crash me3explorer, but there were other similar popups I saw. I'll try to get screenshots out later.

**Comment by KFreon** [comment]
If you could run that in VS Creeper, that'd be great.
I did a few tests and couldn't crash it.

Also, if there's a few that crash, links would be useful.

**Comment by starkgate** [comment]
I think I isolated 3-4 different errors, I did the test with a few dozen TPFs for ME2 and ME3. Links are below. I suspect some of these problems may be caused by 'duplicate' textures, a texture whose hash is used multiple times by the game with different names. There is usually only one of those in a TPF, but if TPF/DDS extracts every texture it recognizes, it will extract more than one. Dunno if I'm clear enough^^.
Error 1_1 :
![error1](https://cloud.githubusercontent.com/assets/12874678/12917146/f06451ac-cf37-11e5-9667-4570cf71c472.PNG)
Error 1_2 :
![error1_2](https://cloud.githubusercontent.com/assets/12874678/12917150/f070227a-cf37-11e5-99c6-d1d6266450b7.PNG)
Error 2 :
![error2](https://cloud.githubusercontent.com/assets/12874678/12917149/f06fecf6-cf37-11e5-980c-368552c7d6dd.PNG)
Error 3 :
![error3](https://cloud.githubusercontent.com/assets/12874678/12917147/f06b8a76-cf37-11e5-97b2-184d8d42f332.PNG)
This one is special, it is due to TPF/DDS trying to extract a .mod. A simple filter for TPFs should suffice to fix it :). Error 4 :
![error4](https://cloud.githubusercontent.com/assets/12874678/12917148/f06e504e-cf37-11e5-828a-5322191b9845.PNG)
The TPFs in question : https://mega.nz/#!B51ESSKZ!0dxdKaNbnL1LQ6GtXNNdqBWi520dZk_-ByqI_a2yO8Q

**Comment by ghost** [comment]
@KFreon -- I was going to upload the TPFs, but Git wouldn't let me. I'm guessing the files were too big. I'm not sure I can find download links for them again, so I'll upload to Mediafire and relink for you.

**Comment by KFreon** [comment]
EDIT: Only noticed the attached TPF's after I submitted. Left the explanations for posterity. 

@CreeperLava : 
1) Looks like a corrupted TFC, but you say you can extract it solo and it works? Interesting...

2) This one is interesting. That error tells me that the number of Hashes is different to the number of things in the TFC (according to me), and is likely due to duplicates, as you said.

Further research for this one: Get to that error state again and go to the locals tab (bottom left where all that red text is) and see if zippy is there. 
If it is, expand it and its Entries property then their names so I can see what's in this TPF, and why it might have done this. 
If it isn't in the Locals tab, just right click "zippy" and go Add Watch, and do the above.

3) Same as 2. The number of detected hashes is different to expected.

4) How'd you get it to extract a .mod through the bulk interface?

**Comment by starkgate** [comment]
1) I checked again, I wasn't able to manually extract that specific TPF actually, it throws the same error upon loading. I'm sure texmod could at least read the content (ie number and names of DDS'), didn't check in game though.
2)The TPF contains 6 textures (7 if you count the .log). 3 of them are duplicates.
Here is a screen :
![capture](https://cloud.githubusercontent.com/assets/12874678/12973738/e9b0adce-d0ae-11e5-81e4-b820f3f037dc.PNG)
![capture1](https://cloud.githubusercontent.com/assets/12874678/12973739/e9ccd562-d0ae-11e5-9ea2-2a58dce5848c.PNG)
4) The .mod was in the same folder as the other TPFs, I have no idea why TPF/DDS thought it could be extracted^^.

**Comment by KFreon** [comment]
1) We might be able to recover data if you want, but I can't really fix a broken file that that in the code.

2) Roger that. Now if a file exists while it's extracting e.g. duplicates, it'll just skip it.

3) Whoops. It tried to extract anything in the folder...Lucky it didn't find something else like a .zip or something.

**Comment by starkgate** [comment]
I'd appreciate it if you could extract that TPF, but don't bother if it takes too much time. I don't think any of these textures would be interesting for ALOT anyways.

**Comment by KFreon** [comment]
Looks like I can't get anything out of it :(
Don't really know about TPFs internally so there wasn't much to try really.

**Comment by ghost** [comment]
Verified in rev745.
