### ISSUE TITLE
Force me3explore closing when stalling

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#17]
You know this window that pops out when you try to close me3explorer while it stalls ? Two options are given : Yes (close me3ex) and No (don't close it). 
Well, turns out selecting Yes never manages to close it, but selecting No does. This behaviour is not consistent, so I guess the whole function is not working as it should.

**Comment by Mgamerz** [comment]
Can you provide a picture for more info?

**Comment by starkgate** [comment]
![capture](https://cloud.githubusercontent.com/assets/12874678/9057606/80bf317c-3a9b-11e5-9111-a53fad80bae2.PNG)

**Comment by Mgamerz** [comment]
Seems like maybe the buttons are reversed. I'll handle fixing it in a
couple hours when I get the chance.

**Comment by Mgamerz** [comment]
Since I'm not the dev on this tool can you give a better description of what's happening. This appears to be part of TPFTools, and I see it's looking for Yes to run some extra code to close it. If you choose no it immediately goes to the block below, but if you choose yes, it does the middle step and then the last one.

```
private void Form_Closing(object sender, FormClosingEventArgs e)
        {
            if (CancelButton.Visible && MessageBox.Show("Background Tasks are running. Are you sure you want to close?", "Reeeally sure?", 
              MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == System.Windows.Forms.DialogResult.Yes)
            {
               //You selected yes, really exit
                cts.Cancel();
                e.Cancel = true;

                Task.Run(() =>
                {
                    while (!OverallStatusLabel.Text.ToLowerInvariant().Contains("failed"))
                        System.Threading.Thread.Sleep(100);

                    DebugOutput.PrintLn("-----Execution of TPF/DDS Tools closing...-----");
                    CurrentInstance = null;
                    SaveProperties();
                    this.Close();
                });
            }
           //You selected no, don't exit, or yes already finished executing. Which is odd, since it's running in the background thread.
            DebugOutput.PrintLn("-----Execution of TPF/DDS Tools closing...-----");
            CurrentInstance = null;
            SaveProperties();
        }
```

I am unsure why one has this.Close(); perhaps it is becaues this is already in the closing method. I am not sure what's blocking. The bottom block executes immediately if the cancel button is missing, which I assume implies there are no background tasks running - If you choose no, it still executes that block anyways, which is why I assume it closes. Something is either crashing or blocking it from finishing this method.

**Comment by HeffU** [comment]
The logic here seems largely confused, and I assume that it's the product of several iterations where background tasks have in fact crashed, thus never completing, and so things were added to counter that.

I'm going to assume that the if-block was assumed to be for the "No" alternative, and simply remove the whole task block as it doesn't make sense that it closes after a while even if you chose no.
