### ISSUE TITLE
rev738 Autofix removes red layer

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#190]
Autofixing any texture results in the red layer being stripped out. Also, the previews in TPF/DDS don't have a red layer either.
![sans titre](https://cloud.githubusercontent.com/assets/12874678/13198479/bf4a1b3a-d809-11e5-8d2b-8a892eb76902.png)
http://filebin.ca/2Xe46HDmD0PM

**Comment by KFreon** [comment]
You manage to find the weirdest stuff...
First thing I notice is the texture is 504x504, which is weird.
Second thing, saving as DXT5 fails on for me.

**Comment by starkgate** [comment]
Oh. Oops, didn't see it was the 504x504. Oh well, the result is the same, the dimension isn't the cause of the problem here.
I will continue to find weird things so that this stable never gets out. I want to keep you with me, forever...

**Comment by KFreon** [comment]
So I fixed DXT crash (was due to some changes on my end), but I still get the red channel.
I-I'll test on Windows 7 ok? [Is...is that ok?](http://0.media.todaysbigthing.cvcdn.com/52/38/4c2e69d780ac7095321d626dd012cc65.png)

**Comment by ghost** [comment]
Uh, I think I just found something else that this issue is affecting.

Look at what happens to the texture when I double-click on the thumbnail in Texplorer to enlarge it:

![redchannel1](https://cloud.githubusercontent.com/assets/13645804/13292141/70c80990-dacf-11e5-9236-e05c4cbdc57b.PNG)
![redchannel2](https://cloud.githubusercontent.com/assets/13645804/13292146/72d082b2-dacf-11e5-8ef6-a015d714c7ed.PNG)

All the data for the red channel is lost.

And looking at basically all other thumbnails similar things happen. With rev738 the enlarged image never matches the thumbnail. This is especially evident with masks. For example, look at this hash (0xD2CB5050) and all the other textures in the same folder. But, it literally happens with everything.

Guessing it has something to do with that new MS code we just bundled in. Can verify it's fine in r733.

**Comment by starkgate** [comment]
It happens for pretty much every tool that displays textures, which is normal since the bug probably comes from a central function that is used everywhere.

**Comment by ghost** [comment]
@CreeperLava -- Yes, especially if it's a result of the new MS code, as I said above.

What's strange is that it's not affecting the thumbnails. Why not the thumbnails and everything else?... Oh wait. I know why. I copied the thumbnails from my old tree scan -- which was with rev 722. I bet if I...yep, if I regenerate the thumbnail then it looks like the enlarged image. Ha ha.

Yeah, so this is a pretty large problem then if the toolset is no longer reading the red channel properly. I'm going to wait on treescanning and test-installing textures until the next rev then.

**Comment by starkgate** [comment]
Tree scanning is probably fine, you'd just have to regenerate the thumbnails in the next rev. I personally don't care a lot about thumbnails, since there's always the option of double-clicking to see the texture.

**Comment by ghost** [comment]
@CreeperLava -- Well, sure, but you don't want to have to double-click every texture to see an accurate representation of what it looks like. The entire point of a thumbnail is to show an accurate representation of what the texture currently looks like >.>

**Comment by KFreon** [comment]
Fixed.

**Comment by ghost** [comment]
wewt

**Comment by starkgate** [comment]
Confirmed to work in rev743.
