### ISSUE TITLE
rev738 Wrong MIPS generation ?

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#193]
This one is a bit tricky. Basically, rev738 seems to generate less MIPS than 718 when autofixing. 718 generates all the MIPS till 1x1, just like PS, whereas 738 seems to act more intelligently by not generating the MIPS not present in the tree

The resulting texture is recognized as correct by 717, but trying to install it in 717 stalls me3explorer (reported by multiple users of ALOT for ME2 and ME3, which is why I have to regularly update the mod^^). Haven't tried installing in 738 yet, I must reinstall ME2, but if someone can try that and give the results, it would help.

If the stall only happens in older revs, it doesn't really matter, as we'll recommend the new stable anyways.

Test files : http://filebin.ca/2Xj7RQ74YcTr
In these files, the 738 is 8 Bytes smaller than 718/PS

**Comment by KFreon** [comment]
Things look fine for me.
By that I mean that I use DxTex to open dds' that I save. Since DxTex is the extremely intolerant Microsoft DDS tool, if it can open it without issue, I consider it basically correct.

So I figure it works ok in 738.

EDIT: I don't have ME2 installed to test either :P I'll try get it installed and see what happens.
