### ISSUE TITLE
rev738 Image Engine alpha problem

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#201]
Loading a texture, switching the display of the alpha channel then clicking convert gives this :
![ie5](https://cloud.githubusercontent.com/assets/12874678/13361378/95aff8ee-dcbe-11e5-9536-30e18d6f885b.PNG)
Nothing wrong here, but if I switch off alpha display, the convert preview still keeps the alpha : 
![bug](https://cloud.githubusercontent.com/assets/12874678/13361359/7cd6d018-dcbe-11e5-838f-2e039e4d1a13.PNG)
Switching to another conversion format then back again to eg DXT5 doesn't fix it.

**Comment by KFreon** [comment]
That's because the alpha is still there, the main preview just doesn't show it.
You think there should be an option to strip out the alpha from the saved image?

I added that "show alpha" toggle because often images have alpha and you can't tell what they are, so I wanted to be able to see RGB only. Many tools have that, and it doesn't affect the saved images because it's preview only.

I'm kinda reluctant to add such an option to saving, because this isn't meant to be an editor. DxTex can't strip out alpha either.

**Comment by starkgate** [comment]
Oh, I didn't mean 'remove the alpha from the converted texture', just remove it from the preview (ie not show it). It's simply to be coherent, if I switch on and off the alpha, I want to see the result on both pictures. If people need to remove the alpha entirely, third party tools should be enough.

**Comment by KFreon** [comment]
Fair point. Consider it done.

**Comment by starkgate** [comment]
Confirmed to work in rev743.
