### ISSUE TITLE
rev738 TPF/DDS Tools Delete page

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#207]
The name of the textures is cropped out in the delete tab of TPF/DDS Tools.
![capture](https://cloud.githubusercontent.com/assets/12874678/13381150/8a2cc596-de54-11e5-8c00-0a494d8aaf39.PNG)

**Comment by KFreon** [comment]
I facepalmed so hard when I remembered this monstrosity existed.
It seems simple, but it's a huuuuge amount of effort to get that fixed.

**Comment by starkgate** [comment]
We debated it yesterday with giftfish. The best thing to do would probably be to integrate the delete function to the main tab (ie add the ability to do multi selection, and add a button to remove all selected textures). The delete page could be used as a trash, to store the remove textures. Or be removed entirely.

**Comment by ghost** [comment]
Yeah, I was going to submit this, this morning, but Creeper beat me to it :)

This "Delete" Tab is actually really confusing. 

You open a TPF and all textures are depicted on *_both *_pages/tabs. So, the logical question then is: what's "deleted" and what isn't? 

It's also not straight-forward that the "Delete" key works to delete a texture, since in general, that key doesn't work in most toolset tools. I was looking around for a "Delete button" in the UI, or a right-click context option associated with the texture and then Creeper told me just to use the Delete key, lol.

Logical behavior would be the following:
-A TPF/DDS/MOD is loaded and all the textures appear in the Main Page
-The Deleted Page is empty upon loading a file.
-If a texture is deleted it is removed from the Main Page and added to the the Delete Page

If this can't be implemented, then I'd suggest just removing the Delete Page. As long as the tool will install only the _selected_ textures, "Delete" really isn't necessary. I actually have a different Issue for that, though, lol.

**Comment by starkgate** [comment]
>  As long as the tool will install only the selected textures

What do you mean by that ? I think having a delete function (a button or something) is important, even if we decide to remove the Delete page.

**Comment by ghost** [comment]
@CreeperLava -- Yeah, see #211 . ModMaker has "Save/Install Selected" options. I'm actually shocked that TPF Tools doesn't have this, and apparently it really doesn't. There's no way to select specific textures in a TPF and install them?

How ModMaker does this with jobs is actually much more straightforward. If you leave it at the default and don't select any it will install all jobs. Or, you can select _specific_ ones and it will install only _those_. I'm still sitting here trying to figure out why TPF Tools doesn't work the same way, when they are such similar types of tools. 

I think the Delete Page just makes things complicated. Just have people select the specific textures they want if they won't want to install everything. I think keeping the usage consistent across both tools would be a very good thing considering how similar they look, and the fact that the same users are probably using both.

**Comment by starkgate** [comment]
> I think the Delete Page just makes things complicated. Just have people select the specific textures they want if they won't want to install everything.

Not a good idea, most people won't notice it works that way and will then go complain to the modders that the mod didn't install correctly :/. You don't have this problem with ModMaker, since most users are already modders.

**Comment by ghost** [comment]
I'm confused as to what you mean by "most users are already modders"? We have _just_ returned modmaking functionalities to ModMaker.

**Comment by ghost** [comment]
Either way, we have two tools that look almost identical in GUI: ModMaker and TPF Tools. They also serve almost identical functions: one installs MOD files and the other TPF files (generally). And yet, you can "Install/Save Selected" in ModMaker, but not TPF Tools.

I get that due to ALOT, you might not want to deal with users learning how to use the new feature in the tool, but I don't think that's a good reason to not make what seems to be a very logical change. Especially considering the current "Delete" method doesn't make sense, anyway, and it's possible K could lift a bunch of the code from ModMaker.

**Comment by KFreon** [comment]
The delete page is for deleting more than one thing at once, not for capturing those things that have been deleted.
That's why I hate it so much. It should be simple to delete from the main page, but apparently it isn't.
You can only delete one by one from the main page, whereas if you want to delete a bunch at once, you go to the Delete page.

As for "Install/save Selected", you can but only one at a time for the same frustrating reason as above.

Why is it different for Modmaker?
-Amusingly I can't quite remember, but I think it was due to how the duplicates were handled. 

Can it be fixed?
-Certainly, by using WPF.

Is that going to happen for the stable?
-Certainly not.

I could probably adapt the Delete page to do it, in fact it probably wouldn't be hard.
It'd be renamed "MultiSelect" or something.

Why don't we just make that the main page? 
-Because duplicate handling breaks.
Do we care? 
-Too bad now unfortunately. Can't be undone without much effort.

So yeah, let me know if we want to change that Delete page to be more useful and obvious as to its function.

EDIT: I've had a bit more of a think about this. It'd still be a tonne of effort to change, but probably not as much as I thought. I'll see how I go.

**Comment by ghost** [comment]
@KFreon -- Okie doke. Let me know if we need to bounce ideas around on Skype. If it's possible to just make a multi-selectable interface like ModMaker, that would be ideal :)

**Comment by KFreon** [comment]
See #211
