### ISSUE TITLE
Remove TOC Editors, or AmaroK86 TOC Editor?

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#214]
@SirCxyrtyx -- This is probably one for you, but @KFreon , you might have some thoughts on this.

I was attempting to finish the wiki article for the TOC Tools and ran into problems.

First, I think both TOC Editors are likely deprecated with AutoTOC. Their code probably hasn't been touched since 2013. We very likely no longer need them. I might be missing some use for editing over autotocing, but I can't imagine what it would be. As far as I know, autotocing is capable of more than either TOC Editor... which is why it was created.

If we retain them, AmaroK86's version throws an error when I try to open the TOC for the base game. No idea why. My current TOC was created with autotoc and allows me to play the game fine. 

I can open BackOff's TOC (also created with autotoc, but every entry is highlighted in red. I'm assuming that's bad, but there's no forum documentation of what it means. From what I can tell, it's actually comparing the DLC mod file to the base game, expecting it to be the same size. Obviously this isn't necessary.

So, yeah. As I wrote all the wiki articles for the User Tools, we ended up removing a lot of deprecated tools from the toolset. I expect the same thing will happen with the Developer Tools, though I'm not quite ready to start on them all yet. This article was just sitting around half done and I was trying to check it off the list.

**Comment by SirCxyrtyx** [comment]
I can't think of a reason to have anything other than AutoTOC. If no one else objects, I can remove TOCEditor and TOCEditor(AK86) when I get home tomorrow. What about TOC.bin Updater? Any reason to keep that around in the age of AutoTOC?

**Comment by ghost** [comment]
@SirCxyrtyx -- Let's wait for K to jump in just to be sure, but yeah, I think all those can be removed. Regular TOC and both editors. Obviously SFAR Tocing needs to stay, since (maybe) someone might need it, but Autotoc covers all 3 of the other tools you mentioned.

**Comment by Mgamerz** [comment]
TOCEditor (not sure which one) is part of the ME3Explorer command line tools. Removing it would break some tools others have written. It is also the only way to modify a TOC for files in an SFAR externally (which is very useful for MP mod building since unpacking MP DLC is not as useful as SP).

It would be easy to hide it from the menus, as long as you leave the onClick methods in.

**Comment by ghost** [comment]
1. Which tools use command line for TOCing? All TOCing inside of tools has been removed with the exception of K's tools and DLC Editor 2, and all of them already use autotoc.
2. _If_ the command line content is necessary to keep, then why not just move those features to autotoc (which isn't deprecated). That way we can strip out all unnecessary code, which the toolset already has too much of.

**Comment by SirCxyrtyx** [comment]
Mgamerz, isn't SFAR TOCEditor the correct tool for editing unpacked dlc TOCs?

And I hadn't really planned on removing the code, just removing the menu options. As messy as it might be code-wise, removing code on a project this size, where no one person actually knows what everything does, is not really a good idea. Same reason that game developers leave cut content in game files.

**Comment by ghost** [comment]
@SirCxyrtyx -- Blarg, about the code. My understanding is that it's a mess and could benefit from some serious trimming... and probably re-writing.

**Comment by Mgamerz** [comment]
External tools from me3explorer. Dybuk and I have used them to build files for different mods because doing GUI takes multiple clicks and takes lots of times when done repeatedly. We have scripts built that are quite extensive for some of the controller mods that depend on it. These command line arguments allow external programs to interface with me3explorer (such as cmd) without having to write more code.

I am not sure if you guys renamed the toc tools recently, but its the one... Kfreon made? There's one by amarok that has this technical stuff and the simple one, but I don't know what it was ever truly named. The simple one is used by command line so one can update specific entries which is useful when you don't have all mod files or want to leave existing entries. Very useful if you have a large size for files, shrink them, and then don't need to ttoc again because the size is already sufficient. These commands are documented on the me3explorer wiki. 

I also agree, if you are closing in on a stable, now is not the time to be actually removing code. Hiding elements is much safer.

**Comment by ghost** [comment]
@KFreon -- Please chime in on this when you can :)

**Comment by SirCxyrtyx** [comment]
I think I will remove the AmaroK86 TOC Editor completely actually. Doing so would allow me to remove the whole AmaroK86.MassEffect3.ME3Directory project. It's been deprecated by code in KFreonLib, and that would mean one less dll cluttering up the output folder.

Edit: Looks like that would also allow to remove the AmaroK86.INIHandler project. Two fewer dlls!

And if KFreon did a little refactoring of KFreonLib.Textures.ME3SaltTexture2D.AddToTOC(), an additional two dlls, AmaroK86.MassEffect3.TOCHandler and AmaroK86.MassEffect3.WindowProgress could be removed. Seems like just running AutoTOC would be better than its current behavior of editing a single entry in the existing one. That might be a bad idea though, since it's a change to what I assume is core texture functionality.

**Comment by KFreon** [comment]
I too wouldn't be removing the code, just the menus. Obviously this adds mess, but with VS it doesn't get in the way :)

@SirCxyrtyx  I don't like removing code, since if I did, the toolset would look rather sparse. 
I got chipped by WV for smooshing some stuff together to save on DLL's. 
Anyway, if everyone wants to, we can, but we aren't saving any space there. Those DLL's are kb's in size.

EDIT: To give some background on why you can't just remove bits of code that are "obsolete": During my WPF rewrite, I binned every other project besides mine to see how much I could remove and still have things work.

It was a waste of time, cos most of them came back because little but central things were required, and I could probably have pulled that functionality out, but it would have been soo much effort.

**Comment by SirCxyrtyx** [comment]
My motive for wanting to remove dlls isn't space, it's the fact that the ME3Explorer folder has a ridiculous amount of stuff in it other than the exe, which is kind of ugly. It's not a big deal though, just a little thing that annoys me.

**Comment by Mgamerz** [comment]
I love the folder named "Stuff". Such a coders project.

**Comment by KFreon** [comment]
It is a mess, but its also handy to have separate projects to separate work. 
One thing we don't use properly is you could update a dll and distribute it instead of the entire toolset. 
I guess that's situational, but still.

**Comment by ghost** [comment]
@KFreon / @SirCxyrtyx -- First, insert non-coder caveat here.

Okay, so this really seems like a no-brainer to me. We have a deprecated tool that isn't used and seems relatively easy to strip out. Removing it also allows us to remove a bunch of other unneeded stuff. All I hear from you guys and @HeffU is that the toolset is a bit of a mess ("spaghetti code", and the like), so in a situation like this where it seems reasonably easy to get rid of unneeded code, why not do it?

I mean, I get that there is risk involved; I assume, though that VS provides you with detailed data about how/if certain files are are used, right? It's not like we have to guess, correct? Also, I get that WV was opposed to removing stuff, but, well... he's not here. He hasn't been involved in the toolset for a very long time, actually. He has gone the way of Lucas. He made much of the toolset, but he's no longer its keeper. You two have the freedom to do what you think is best, just as Disney is doing with Star Wars.

Finally, there is of course the fact that we can, you know, test these changes :)

**Comment by Mgamerz** [comment]
VS can only detect some issues. Remember how I broke pcceditor2? Visual studio couldn't detect that (curiously...) That's the same situation if code starts being removed. 

The project is so big that going through and verifying everything works would take a really long time. It would be the run time errors that are the issue, VS can figure out just about all compile time ones.

**Comment by KFreon** [comment]
It's not that we can't, but I just don't like to either. 
For one, it helps those who do use the toolset for other things while simultaneously preventing users from using whatever we don't want them to.

I feel like we can cleanup things once the stable is ready. That way, we have something that works to compare against after things get removed.

Sir, you can do as you please, you are coder after all. You want to remove stuff, go right ahead. 
I'm just saying I won't be just yet.

**Comment by ghost** [comment]
Verified in rev742.
