### ISSUE TITLE
r742, Texplorer PF_DXT5 != DDS_DXT5?

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#240]
Uh, so yeah. This is an interesting one:

![texplorer_dxt5error](https://cloud.githubusercontent.com/assets/13645804/13825950/4e051b7e-eb72-11e5-8cd9-9f40a5727724.PNG)

All ME1 DXT1/5 textures are "PF_DXT#". I haven't made any other trees, yet, so I don't know about ME2/3. _EDIT: Okay, same thing for ME2. All textures have the "PF_" prefix._

DXT5 is supposed to be the same as BC3, though, and I've never had any problems with the tool using all my DXT5's in the past. I have no idea what the "PF_" means and know I don't talk about it on the wiki at all. GIMP also has no option for "PF_DXT5" when saving DDSes.

Current stable uses "DXT5" for ME3, "PF_DXT5" for ME1/2. As far as I can tell, they are all the exact same texture format. 

_EDIT: Same deal for DXT1._

**Comment by ghost** [comment]
More info.

ME2 throws the same error when replacing a simple DXT1 codex texture without mips:

PF_DXT1 != DDS_DXT1.

By "replace" I mean "Add Bigger Image". The "Replace" feature throws the mipmaps error in #239 .

**Comment by ghost** [comment]
@CreeperLava -- I'm surprised neither you or Alvaro reported this issue. Have you guys tested texture installation with Texplorer for ME1 and ME2?

**Comment by KFreon** [comment]
I have had it with this method of format detection.
I'm going to replace the whole lot with a proper enum so there's none of this rubbish.

**Comment by ghost** [comment]
Sorry, @KFreon  <3

I always feel like the bearer of bad news >.<

**Comment by starkgate** [comment]
@giftfish I usually only test TPF/DDS Tools, and nobody reported issues with texture installation in ME2 using rev717 or rev741 (not from ALOT at least). Haven't had the time to properly test the new revs in a while too, but that's definitely something I'll do this week-end.

**Comment by ghost** [comment]
Well, this is via Texplorer, though, not TPF Tools, and with rev742, not 741.

Tthat might account for the problems, whatever they are. It's been a long time since I tried using Texplorer to install an ME1 texture, but last time I did, I know it wasn't throwing this error, and I am using the same textures.

**Comment by KFreon** [comment]
This is just the old way of doing things rearing its ugly head.
Some background:
Existing:
- string comparison. i.e. DXT1 is NOT dxt1, etc. It's just text, fraught with problems.
- likely done due to laziness and ease of using strings. Maybe also because there were only a few formats at the start.

New:
- Nice pretty enum. So there is only one way to say DXT1, there is no dxt1 or PF_dxt1 etc
- Going to take work, but only error is if I type the wrong one in.

**Comment by ghost** [comment]
I was actually wondering if that was the problem -- just a string comparison. 

Why does it work in TPF Tools, @Kfreon? And, why haven't I had the same problem with ME1 in the past? It seems like something changed, somewhere.

**Comment by KFreon** [comment]
1. Likely it works in TPFTools because I sanitise the format a bit more cos that's where I spend more of my time. 
2. It would have become more prevalent after adding the ImageEngine which uses that enum method instead of strings. The conversion and subsequent sanitisation clearly doesn't catch everything.

**Comment by ghost** [comment]
@KFreon  -- 

Same deal as #239. I haven't been able to verify scanning and texture replacements on ME1 and ME2 yet due to the pathing bug, but things are working properly now for ME3. Tested DXT1 and DXT5.

Verified in rev745.
