### ISSUE TITLE
rev743 Suggestions : TPF/DDS Tools

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#248]
Just a few ideas :
- Add the ability to use the space bar to check and uncheck files. It's just sooo much better than to click on the tiny checkboxes : just press space bar, down arrow and repeat.
- This one may be more difficult to implement. Can we get multi-selection with Ctrl+Click and Shift+down arrow ? Then check all the selected by pressing space bar ?
- Improve the button layout a bit : instead of having this
  ![capture](https://cloud.githubusercontent.com/assets/12874678/13903536/b9eeeb8e-ee7f-11e5-9cfc-d203ec20ebe8.PNG)

Have something like : "Apply only to checked : 'Install' 'Autofix' 'Extract' | 'All the buttons not related to the checkboxes are after the bar'"
This avoids to repeat 'checked' 3 times and gives a clear separation to what applies to checked files or not.

The 3 buttons 'Analyse with Texplorer', 'Install Valid' and 'Autofix and Install' should probably be changed too to reflect the recent changes. It feels like there are way too many buttons visible in TPF/DDS, it's quite overwhelming. I'm not very good with organizing stuff, but maybe giftfish could help here ;).

Also, the 'Extract' dropdown menu and 'Run Autofix' button in the top menu, are kind of redundant with those at the bottom. They could probably be merged in 2 dropdown menus at the top, eg :
Extract
. All
. Checked
.. All
.. Invalids
.. Valids
. Unchecked
.. All
.. Invalids
.. Valids
It is a bit of clutter and can surely be improved, but at least you have all the options there. Same for autofix :
Autofix
. Checked
. Unchecked
- Add a color change (eg the same color as when you select something) to selected files, instead of just having the teeny tiny checkbox as a visual confirmation. This would go nicely with the multi-selection.
- For now, if I check a file, then autofix it, the resulting file is unchecked. Which could be annoying if you are trying to keep track of what you are editing.

**Comment by KFreon** [comment]
- Check by spacebar = done.
- Multiselect = Not feasible. That's the point of the checkboxes :(

Mkay, so yes, these buttons could work better, but it's fiddly to move them. Besides, the usual Windows style is for Top menus to work on large groups/everything, and more localised buttons work on the local thing it's near.
I know it's not ideal, but just dragging menus around isn't as easy as it sounds.
Unfortunately, it's not that easy in WPF either. UI design is hard, or I just suck at it :P

**Comment by ghost** [comment]
@KFreon -- I'm really not digging the change where a texture is automatically checked when you click over/arrow through it.

The problem is this: in order to preview of the texture, you have to highlight/select it. Previewing is necessary since the thumbs are too small to convey detail. Highlighting is only achieved by clicking/arrowing through the names. With how you've changed it, though, it's now impossible to simply highlight the texture to preview it and not cause the box to be checked. Which then means you have to click/highlight again to deselect it if you decide not to use it. It's also impossible to immediately deselect by clicking the name; you have to select a different one and then go back, OR click directly on the tickbox itself. 

Another (even bigger) problem is that the autoselecting actually makes the ability to arrow through and only select _specific_ textures pointless. It ruins the ability to repeatedly arrow up and down the list, only selecting the textures you want, b/c every time you arrow over something it will select or deselect it. In other words, if you ever need to backtrack/jump forward, you'll end up having to use the mouse to avoid borking the rest of your selections.

Please revert the autoselect and only implement Creeper's suggested spacebar change. That's a great idea, since it's a specific action and it's an easy key to hit with one hand, when arrowing or mousing with the other.

**Comment by ghost** [comment]
@KFreon -- We also seem to have lost a couple buttons recently.
- "Install" used to be an option on the bottom, next to Extract/Replace/Convert. This entire context menu only affects _selected_ textures, which means right now there's no way to install only a specific subset of textures inside a TPF (see #211). 

What we need at the bottom is:

Checked: Extract Replace Autofix **Install**

Why was this removed? It's been done at some point since I wrote the wiki article; perhaps at the same time that you removed "Convert"?
- Removal of the very bottom, larger "Autofix and Install" button is probably fine. It was nice to do both in one click, but it isn't a huge deal that you can't anymore. I actually think it's better do both actions separately, so any potential problems can be addressed prior to install, not as _part_ of the install process.

**Comment by starkgate** [comment]
@giftfish The Install button is definitely there for me in 746.
I agree with gift on the checking upon selection thingy, we would be better off without it.

**Comment by ghost** [comment]
I'm glad you said that, @CreeperLava. It's b/c "Install" doesn't appear unless there are trees present and you've analyzed with Texplorer. I apparently tried it yesterday before I made my trees.

So, false alarm on that @KFreon ; just the checkbox/spacebar issue, then :)

**Comment by KFreon** [comment]
Done.

**Comment by ghost** [comment]
Love this spacebar-select addition.

Verified in rev747.
