### ISSUE TITLE
Rev 744 - TFP/DDS Tools image preview cache not refreshed when deleting textures

### ISSUE THREAD

**Issue by alvarome** [ME3Explorer/ME3Explorer#256]
Hi:

This rev744 -and I also can confirm this in 741 too- have the bug already reported for rev738 and fixed in rev739.

TPF/DDS Tools: when a texture is selected and deleted, the preview image is not updated.

Loos like the bug returned when the interface was simplified as we have no "main page" and "delete page" tabs now.

HTH
Alvaro

**Comment by ghost** [comment]
FYI, main and delete pages were not working as intended, which is why they were removed. There's an issue around here somewhere that contains the discussion. 

Now, all you do is "Run All", or select the textures that you want and "Install Selected". If you want a TPF that contains only those selected textures (for whatever reason), then "Save Selected to TPF".
