### ISSUE TITLE
Bug v744 - Adding names to an array in Interpreter

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#257]
If you have an array with names and select "Arrays: Name Table" then try to add an array item, it adds a single integer (8bit) to the array not a 16bit name.

If you add 2 integers to fix this (the name ref and 0) it increases the count by 2.

Similarly deleting removes only the the single integer.

**Comment by SirCxyrtyx** [comment]
I fixed the deleting part with commit 3052cc70492e924b13523ebf3579b9c1560b9e26, so that will be in the next release

The adding is a bit more complicated. I can detect if it's a name array when there's already entries in it, but if it's empty, the program doesn't know what kind of array it is. Would it make sense to change the behavior of adding to an empty array based on the selection in the array dropdown? If raw or import/export is selected it adds 4 bytes, if names is selected it adds 8 bytes?

**Comment by Kinkojiro** [comment]
Yes, by far the best way would be adding and deleting based on what the user actually sees at that point (as the drop down is set).
