### ISSUE TITLE
rev746 ME2 DXT5 to DXT1 conversion

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#277]
DXT5 to DXT1 is buggy, I ended up with an entirely black texture for each conversion. I haven't tested it in ME3.
Test files : https://mega.nz/#!A5Vhgaba!ji5Sksj0n1FtyJQVBRVefFMEFShjW81p6ismMf3VF8A
The black textures are the autofixed ones, the others are the originals.

**Comment by ghost** [comment]
@CreeperLava -- Is this for the Image Engine or TPF Tools?

**Comment by starkgate** [comment]
TPF/DDS Tools, but the problem will most likely be the same in IE.

**Comment by KFreon** [comment]
Given ImageEngine is the base of all image work in the entire toolset, it's always due to ImageEngine :P 

Fixed kinda, so I'll explain.
- DXT1 is 1 bit alpha, which means a pixel is either transparent or opaque. There's no gradient here.
- There's a threshold for alpha that kinda needs to be hardcoded.
- It was set at 80%, which means anything that's >80% opaque is made 100% opaque and everything else is transparent.

EDIT: I made it 20% now.

**Comment by starkgate** [comment]
Awesome, so we have a way to create DXT1 with alpha automatically now ? This is very good news !

**Comment by KFreon** [comment]
It's...always done that?

The threshold has been 80% though, so that'd cut out most of the alpha.

**Comment by starkgate** [comment]
I never noticed it then, I thought it would systematically delete the alpha when converting to DXT1.

**Comment by ghost** [comment]
@KFreon -- 

> Given ImageEngine is the base of all image work in the entire toolset, it's always due to ImageEngine :P
> 
> Fixed kinda, so I'll explain.
> 
> DXT1 is 1 bit alpha, which means a pixel is either transparent or opaque. There's no gradient here.
> There's a threshold for alpha that kinda needs to be hardcoded.It was set at 80%, which means anything that's >80% opaque is made 100% opaque and everything else is transparent.
> 
> EDIT: I made it 20% now.

This seems... strange. It also makes me wonder if it generates some of the strange alpha-issues I experience in GIMP when extracting facial textures. You know, the ones that look like this, and are therefore impossible (or really difficult) to edit:
![alpha_compare](https://cloud.githubusercontent.com/assets/13645804/14060701/6e85a7ba-f329-11e5-8198-18f089d893fa.PNG)

Or this disparity between the same DXT1 eye texture in two different revs of the toolset:
![dxt1compare](https://cloud.githubusercontent.com/assets/13645804/14060768/c64d1d5a-f32b-11e5-83ee-e9719ebd5c4c.PNG)

Is that 80% (and now apparently 20%) number based on something BioWare-specific? How do you choose a number that you know will cause the texture to render properly in game and not cause unpredictable problem, say, maybe like #273?

**Comment by KFreon** [comment]
The value itself isn't specified anywhere because it's usually set by the designer when they're making it. DXT1 just shouldn't have alpha, it does a terrible job of it.
As for the glitches, it is possible this is causing them, but I see no way around it.
The only thing I've thought of so far is to set the threshold dynamically by finding the minimum and maximum alpha values and setting the threshold to half of that.

**Comment by ghost** [comment]
@KFreon -- Hm. This definitely seems problematic. So, basically what you're saying is when we extract a texture, the toolset might be interpreting the alpha incorrectly, and therefore, we aren't _necessarily_ seeing the texture as it was originally created?

**Comment by KFreon** [comment]
No no, just when a conversion is done, like DXT5 to DXT1.
Extracting just gets data, but the conversion has to take 8 bit alpha and try to make it 1 bit alpha, so there's a threshold where anything above the threshold is 100% opaque, and anything below it is 100% transparent.

Before, it was 80%, now it's 20%.

**Comment by ghost** [comment]
@KFreon -- Okay, that all makes sense. I'm really wondering how this will affect how the textures are viewed in the toolset and in game, though. That seems like a significant change, isn't it?

**Comment by KFreon** [comment]
Well back in the day, the alpha was just thrown away. 
For a while now, the alpha has been kept a little bit.
Now just more is being kept, which could make things look different I guess.
I don't know how people want this handled.

**Comment by starkgate** [comment]
The most important thing is that the converted texture should look as close to the original as possible. Which can be difficult for sure when you go from 8 bit alpha to just 1 bit.

**Comment by starkgate** [comment]
There seems to be another issue with DXT5 to DXT1 conversion, this time a quality loss. This was brought to my attention by ElysiumFic :
![dxt1](https://cloud.githubusercontent.com/assets/12874678/14062927/ec5d0e70-f3b1-11e5-9e17-b3da37732c0d.PNG)
![dxt5](https://cloud.githubusercontent.com/assets/12874678/14062926/ec591392-f3b1-11e5-87a9-3ffe1be6b367.PNG)
2 problems :
- Massive pixellation, most likely due to the 1 bit alpha conversion. Could anything be done to smooth the shapes ?
- Why is the texture cropped following the alpha's outline ?
  Test files : https://mega.nz/#!pxVgFQqI!g5yKpbIgFXoGbwUndltkan4Qw9C0phKwZw6usQszurM

**Comment by KFreon** [comment]
DXT1 is massively inferior when it comes to quality compared to DXT5. It can't look the same unfortunately.

I'm not quite sure why it's cut off the RGB there...
The pixellation is caused 100% by the alpha channel being merged somehow into the RGB. That shouldn't happen.

**Comment by ghost** [comment]
Okay... here's a question.

Why would someone need to convert DXT5 to DXT1? Like, if a modder made a DXT5 that should actually be DXT1? If that's the case, then what they're doing is trying to create alpha values that the game isn't really prepared to handle for that texture-specific purpose. Not as far as actually perma-modding the files.

I'd say the answer to that is to run the texture in Texmod.

I guess what it comes down to is that at least in the context of using the texture in game (not just simple converting to convert) there are some conversions that simply don't make sense.

But, I agree with Creeper that the goal is always consistency in appearance with the vanilla game. If there isn't consistency, then there isn't much point. Then folks are just going to hop on the forums and ask "why doesn't this look like X".

**Comment by starkgate** [comment]
Hair mods use DXT5, and they're supposed to run through Texmod so it doesn't pose much problems. Until you decide to install through ME3Explorer, which demands a DXT1. There are also plenty of other mods out there that have just plain wrong formats, that's just how texture modders work it would seem^^.

**Comment by ghost** [comment]
Yeah, the hair mods is part of what I was thinking. Folks try to install them and then wonder why the textures won't work. /facepalm

**Comment by KFreon** [comment]
Often we see DXT5's that are only DXT1's in game, so converting down to DXT1 is necessary. Most of the time it doesn't seem to matter though.

@CreeperLava - I found out some more info though.
- This is absolutely supposed to happen, as in every tool I have does it.
- It's an absolutely weird way of doing it because it's totally unnecessary.

Basically:
- DXT1 uses part of its 5:6:5 RGB to make an alpha, but instead of keeping the 5 bits of green underneath, it sets it all to black...
- EVERY tool does this, so it's not just me.

Interestingly, the only problem you're likely to see with this is the pixellation. All I can suggest is merging the alpha manually, then saving it as a non-alpha DXT1.

**Comment by ElysiumFic** [comment]
Here's the situation: I'm creating DLCs for the hair mods so that no one will ever ask that again (hopefully.) Furthermore, texmod doesn't work for some people (like, um, me.) Even when used correctly, the textures don't show up.

Now, as to the WHY, the texture hair mods were intended to replace, Short02, is the ONLY hair texture that is in DTX1. All the others are in DTX5. Not sure why the modders decided on using Short02 except that it isn't actually used anywhere in the game.

Now, in order to create my DLCs, perma-replacing was kinda a requirement. At Kinkojiro's suggestion, I did a binary replacement to replace Short02 with a bin from one of the other hair textures (the CustomSexy one or whatever it's named, specifically.) That way, ME3Explorer didn't complain about trying to replace DTX1 with DTX5, and there was no need to downgrade the texture.

So my DLC mods DO use DTX5. But that introduces another problem: transparency.

The DTX5 textures have huge transparency issues. If converted down to DTX1, those issues go away, but then there's major quality loss. So I'm damned if I do and damned if I don't, unless I can find a way to fix the transparency.

**Comment by starkgate** [comment]
> unless I can find a way to fix the transparency.

That, or find a way to smooth the pixellated alpha. There has to be a way with some Photoshop wizardry.

**Comment by KFreon** [comment]
@CreeperLava - Certainly, except the toolset isn't Photoshop. 
@ElysiumFic - Try the thing I said above with the manual stuff in Photoshop. Hair doesn't need transparency after all.

**Comment by ElysiumFic** [comment]
I'm trying to figure out Photoshop. Slowly but surely getting there. It intimidates me. Tell me to pick apart a pcc with the toolset, do binary replacements, clone outfits, build DLCs and I'm JUST FINE.

But Photoshop? _whimper_

**Comment by KFreon** [comment]
![image](https://cloud.githubusercontent.com/assets/7845997/14063105/717765d0-f405-11e5-8eab-8cb0f5f0292a.png)
@CreeperLava : This is what came out of a Photoshop conversion btw.

@ElysiumFic - [Try this one](https://dl.dropboxusercontent.com/u/37301843/0x487289A3.dds). I copied the alpha channel out, then saved as PNG, then added a layer mask and pasted the alpha into it, then saved as JPG, then saved as DXT1.
Fiddly...

**Comment by ElysiumFic** [comment]
I will give that a shot, thank you. If it works, I'll have to replicate the process almost 200 times lol. I'll also need to do for the male hair mods the OPPOSITE of what I did for Short02, a swap in a DTX1 texture, since like I said, Short02 is the only DTX1 hair in the game. The others are all DTX5.

**Comment by starkgate** [comment]
@KFreon Another way to do it, which requires less work and could possibly be automated with macros : 
Switch to the alpha channel, go into Select > Color Range and click on the white of the alpha. Set the fuzziness to maximum to get all the shades of grey (no pun intended^^). Go into Select > Inverse Selection. Then go into Image > Adjustments > Hue/Saturation and set Lightness to minimum. Remove the alpha, save as DXT1 without alpha.

**Comment by ghost** [comment]
@ElysiumFic -- GIMP has a BatchProcessor plugin that can do all sorts of basic editing and conversion operations. I'm sure Photoshop has the same thing.

**Comment by KFreon** [comment]
There you go.
I'm a Photoshop noob. It took me half an hour to figure it out the way I did.
Creepers idea sounds better @ElysiumFic.
EDIT: Wait @ElysiumFic, didn't you say most of them are DXT5 in game? Cos aren't all of these hair bits DXT5 too so you won't have to do anything to fix them?

**Comment by ElysiumFic** [comment]
@Kfreon Yes, most hairs are in DTX5. Only the one we're trying to replace is in DTX1, but I got around that by doing a binary replacement of another hair into the Short02 spot, so now ME3Explorer doesn't get grumpy about trying to replace DTX1 with DTX5.

I'm reasonably certain your texture shouldn't look like this: 
![masseffect3 2016-03-26 18-39-52-83](https://cloud.githubusercontent.com/assets/18093925/14063358/a088bb18-f382-11e5-9b5b-8a306f8d1f2b.jpg)

Not sure what that's about. It was giving me weird issues. Texplorer kept telling me it only had ten mipmaps and that it wanted 11, even after I resized it and generated new mipmaps, TPFTools didn't have a problem with the number of mipmaps, no errors whatsoever.

I'm gonna give @CreeperLava's process a go now and see how that turns out.

Yes, the hairs are in DTX5, and if it weren't for the transparency issue, they'd be excellent. As it is, here is how most of them end up looking at various points:

http://i.imgur.com/huRrvks.png

-- you can't tell but that hair is actually supposed to be piled high in a bun on her head. Or maybe not a bun, but a longer style. Anyway, it wasn't supposed to look like she'd clipped it close to her head and slicked it down with gel.

http://i.imgur.com/0QeRmxp.jpg

Sorry, I'm not trying to get you guys to solve this issue for me. I was discussing it with @CreeperLava and he had a question about it and then it devolved into another round of "fix the hair textures". Not trying to derail anything or whatever.

On the upside, so far the DLCs are working for people. If I can perfect them, you will probably get a low fewer people asking why it doesn't work.

**Comment by ghost** [comment]
@ElysiumFic -- If teh replacement size is 1024x1024 (which sounds like it is), the mipmap error is one I've recently reported.

Your screenshots look exactly like what I'd expect with an alpha-related error.

**Comment by ElysiumFic** [comment]
Yeah. The other night I tried replacing the DTX5 alpha with the DTX1 alpha, since DTX1 has no transparency issues and @CreeperLava pointed me to a discussion about ALOT where someone fixed the mohawk transparency by substituting in the alpha from Jame's non-transparent mohawk. Unfortunately, I don't have other similar textures to substitute the alpha of these for; they're all unique

Anyway, I was successful in getting the a DTX5 texture to not be transparent, but unfortunately I had all the same quality issues that come with DTX1.

If I could clean up the DTX1 alpha, it would be great, but then, well, I'm sure it wouldn't be a DTX1 alpha anymore, lol

As for the mipmap error, I believe it was 512x512. But I upsized it to 1024x1024 and generated new mipmaps and it still gave me the error.

**Comment by ghost** [comment]
Yep, it's the 1024x1024 size taht will throw the error in Texplorer. It's expecting the wrong number of mips. Should be fixed in the next rev.

**Comment by ElysiumFic** [comment]
And here's what I get trying it using @CreeperLava's method.

![masseffect3 2016-03-26 19-46-33-39](https://cloud.githubusercontent.com/assets/18093925/14063567/124de95e-f38c-11e5-85aa-b5fd0c437a44.jpg)

Either I'm doing something wrong or the game really doesn't like DTX1 with no alpha for this.

(or it could be that it just doesn't like the hairmods downgraded to DTX1 period; that's probably the biggest reason people don't see the textures, because the conversion to DTX1 just yields very unpredictable results. The ONLY time I've gotten DTX1 to work is when I downgraded it using the DirectX Texture Tool.

**Comment by ghost** [comment]
Does the texture itself look like the bottom one in Creeper's screenshot several posts up?

**Comment by ElysiumFic** [comment]
It does before I follow his method. One sec, I took step by step screenshots in case I needed to find out if I was doing something wrong:

Keep in mind, I am literally learning Photoshop as I do this. I know NOTHING about what I'm doing. NOTHING. Maybe once I get the hang of it I can start to come to my own conclusions, but right now? It's pure monkey-see/monkey-do.
1. Starting point:
   ![01 rgb layer](https://cloud.githubusercontent.com/assets/18093925/14063608/4b3427d6-f38e-11e5-9362-d355852986b7.jpg)
2. Alpha:
   ![05 greyed out in alpha channel](https://cloud.githubusercontent.com/assets/18093925/14063615/a3a4a6fc-f38e-11e5-970f-132e3eda62cc.jpg)
3. Selecting the color range:
   ![03 color range](https://cloud.githubusercontent.com/assets/18093925/14063610/65f34bf6-f38e-11e5-9b1a-429bc46d999d.jpg)
4. After Selection:
   ![04 after select](https://cloud.githubusercontent.com/assets/18093925/14063612/85fdc3d6-f38e-11e5-83db-2c52147c3ed3.jpg)
5. Cannot do the hue/saturation step while viewing the alpha channel:
   ![05 greyed out in alpha channel](https://cloud.githubusercontent.com/assets/18093925/14063617/af98560c-f38e-11e5-90dd-fdedbbd56ec1.jpg)
6. Back in RGB view:
   ![06 rbg after select](https://cloud.githubusercontent.com/assets/18093925/14063618/be204cac-f38e-11e5-9cec-5952c64b0d67.jpg)
7. Yay now I can do the hue/saturation step:
   ![07 hue saturation can be clicked on now](https://cloud.githubusercontent.com/assets/18093925/14063619/c68c4396-f38e-11e5-900b-8ce5bcdf67cc.jpg)
8. The point at which I start going "bwah? This can't be right!" i.e. turning the brightness all the way down.
   ![08 lightness turned all the way down](https://cloud.githubusercontent.com/assets/18093925/14063628/e80dcc38-f38e-11e5-8a37-d554b2adfce9.jpg)
9. Alpha deleted (9 was pretty straightforward right click on the channel and choose delete so I didn't include a screenshot)
   ![10 alpha deleted](https://cloud.githubusercontent.com/assets/18093925/14063630/f2d079d6-f38e-11e5-9c50-7c71d1cc6ebd.jpg)
10. Thumbnail after saving:
    ![11 thumbnail after saving](https://cloud.githubusercontent.com/assets/18093925/14063631/161b669e-f38f-11e5-9174-9bfb576bd99b.jpg)

IDEK. This is way beyond anything I know how to deal with. But, as I said, it could just be that this game doesn't like hair in DTX1. The ONLY time I've gotten it to show a DTX1 texture for hair was when I downgraded using DirectX Texture Tool. I'd be happy to go that route, except quality issues. 

Here's a comparison:
http://i.imgur.com/ol9C4zh.jpg

It demonstrates both the transparency issue and the quality issue (look at the hair line and a few of the wispy bits like the one on the left side of his forehead. It's...scratchy, I guess, is the word I keep coming back to.)

Maybe I should just do a poll and see which one bothers users more.

**Comment by KFreon** [comment]
The DXT1 looks better in that comparison there.
Anyway, it's fiddly and weird, but DXT5 -> DXT1 is never going to be a nice conversion if there's alpha involved.

**Comment by starkgate** [comment]
@ElysiumFic Terribly sorry, I forgot a step in my instructions : after you select and set the fuzziness you need to **inverse the selection** ! Into Select > Inverse (or something like that).

**Comment by ElysiumFic** [comment]
Ah, see, I KNEW there was something not right. Okay, I will play some more. I wonder...if I strip out the alpha, and then convert the Photoshop DTX1 to DTX1 using DirectX Texture Tool, will the game like it better? (since that's the only way I've ever been able to get DTX1 to work with these.)

Gonna try it with a different hair mod because that mullet is not the best one for checking transparency.

**Comment by ElysiumFic** [comment]
Well. Feh. It's not reading the texture that way, either.

![masseffect3 2016-03-27 01-56-34-83](https://cloud.githubusercontent.com/assets/18093925/14064646/5ef76b12-f3bf-11e5-91b5-9e4cc7c0480f.jpg)

It wasn't quite as egregious as the other two tries. This time it was just a more traditional "there is no texture there" as opposed to "wtf is this i cant even."

This game does NOT like DTX1 for hair textures. My only hope for solving the transparency while not sacrificing is going to be to somehow fix it in DTX5. Otherwise I need to suck it up and deal with the "ball point pen vs. paint brush" texture difference.

**Comment by starkgate** [comment]
Here is what it looks like in 747 :
![capture](https://cloud.githubusercontent.com/assets/12874678/14064829/d7cf4ee0-f411-11e5-956c-0b6d89f33427.PNG)
There still seems to be a problem with alpha.
Test files : https://mega.nz/#!4tNVDAhQ!AWdaXkn8bDk-QOijJihmuHYnpAQhvxkInc7GLfUfzms

The hair conversion is very good though, at least as good as the photoshop way to do it.

**Comment by starkgate** [comment]
More testing files : https://mega.nz/#!E0tD3LSI!LGmMBepmJCzZG9tKNfqyntEcZPg5IwfLlDaiF__3wd8
Some DXT5s convert just fine, others are like in the picture above. There is at least one that is still entirely black.
EDIT : The black texture is a texture I ported from ALOT for ME3 (which uses DXT5) to ME2 (which uses DXT1). The alpha is also black in vanilla, which I don't really understand, but this black alpha explains why the converted texture would be black.
What is odd is that the ME2 texture doesn't have an alpha, so wouldn't it be more reliable to simply strip out the alpha in the case where the alpha would be entirely black ?

**Comment by starkgate** [comment]
Here are screenshots that will hopefully help to better understand :
![capture](https://cloud.githubusercontent.com/assets/12874678/14065028/ff66d9f8-f418-11e5-8fb3-adffa5528af9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12874678/14065026/ff659e44-f418-11e5-9cf8-b6193b16e53b.PNG)
The picture above is _vanilla_ DXT1.
![capture3](https://cloud.githubusercontent.com/assets/12874678/14065027/ff65ff88-f418-11e5-9ed5-56cf54ab8c02.PNG)

**Comment by KFreon** [comment]
Ok I tried some adaptive alpha things, but nothing really worked. 
Not sure what more to do.

**Comment by starkgate** [comment]
There has to be a rule, where in certain textures you can simply strip out the alpha to get a DXT1. Most of the textures I sent you can be converted that way. Now this doesn't apply to all DXT5 to DXT1 conversions, which is the problem, some require a merge of the alpha (like hair). No idea how you can recognize which can be fixed by simply removing the alpha though.

**Comment by ghost** [comment]
Well, or, like I said previously, maybe the answer is that certain conversions just aren't allowed b/c of such a large deterioration in quality.

**Comment by KFreon** [comment]
Image engine must allow it since that's it's job, but texplorer and autofix need to be smarter. I'm in the process of allowing the choice to strip it merge the alpha, and I reckon if the toolset does both then picks the biggest one, since it'd be entirely white or black, which would be smaller.

**Comment by KFreon** [comment]
An update:
- The threshold thing has been built into the UI for ImageEngine. 
- There's no way I can think of to sensibly integrate this into Autofix i.e. That font file can't be fixed without breaking other things. Any ideas are appreciated.

**Comment by ghost** [comment]
I guess I'd say to do what will work 99% of the time. If the font thumbs are the exception to the rule, then that might have to be how it is.

**Comment by starkgate** [comment]
I agree with gift, do what works most of the time, and if you can detect the textures that won't work, mark them as autofix failed if one tries to fix them.

**Comment by KFreon** [comment]
I think I got a bit confused between the two issues on this one issue, so I think I jumped the gun.
Allow me to elaborate:

*_DXT1 threshold issue @CreeperLava *_
- I don't really want to mark it as Autofix failed, since it didn't fail, it just looks weird.
- I've built the option into the UI for ImageEngine, so I figure if users come across this issue, they can use it to fix it. 

*\* Font texture thumbnail issue**
- My previous comment about how this won't work was incorrect. I was thinking about saving to DXT1 which is always the same size regardless of content. 
  So here's the plan:
- Make a JPG with the alpha stripped out, and another one with the alpha flattened into the RGB.
- Pick the largest filesize image, as one with poor alpha merging will be smaller due to large sections of black. This was the original problem that caused me to strip the alpha from thumbnails.

**Comment by ghost** [comment]
How's the conversion part of this issue looking, Creeper?

**Comment by starkgate** [comment]
As explained on the forum, apart from a few textures like hair and other very alpha dependant textures, that would need case by case fixing ; the conversions went fine :).

**Comment by ghost** [comment]
Great. Then...

Verified in r748.
