### ISSUE TITLE
rev747, TPF Tools, 2x1 Textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#292]
TPF/DDS Tools doesn't seem to catch wrong ratio textures (like eg 1024x512 instead of 512x512). No warning is given, and the installation seems to go fine. Debug log doesn't say anything either. If I check in Texplorer, the texture is still vanilla after the 'successful install'.

[MASSEFFECT3.EXE_0x77B0B844.zip](https://github.com/ME3Explorer/ME3Explorer/files/206361/MASSEFFECT3.EXE_0x77B0B844.zip)

**Comment by ghost** [comment]
K changed something recently to ensure it caught textures of the incorrect ratio when inserted via the "Replace" feature in TPF Tools. I'm assuming what you're talking about is a texture that has the wrong proportion from the start?

**Comment by starkgate** [comment]
Yes, indeed. If I load any 1024x512 or whatever similar resolution, TPF/DDS won't catch it.

**Comment by ghost** [comment]
That's interesting. There used to be a check for that. I wonder what happened.

**Comment by starkgate** [comment]
Kind of works in rev748. Texture is flagged as DIMENSIONS, but autofix still doesn't work. While this isn't a huge issue, autofix doesn't mark the texture as AUTOFIX FAILED, even though it clearly doesn't scale it to the right ratio.

I don't think it's necessary to make autofix actually work for this type of texture, just have an AUTOFIX FAILED warning should be enough. As you said, it's the mod author's fault for not paying attention^^.

![capture](https://cloud.githubusercontent.com/assets/12874678/14352852/bcdbe53a-fcd6-11e5-8d34-7175da212301.PNG)

**Comment by KFreon** [comment]
I don't know if I want this to say failed since it didn't, it's just the wrong dimensions. The autofix worked fine. 
I see what you mean though. Maybe it should say failed.

**Comment by KFreon** [comment]
Ah I remembered the main reason I don't want "Autofix failed", because it doesn't have to be autofixed to be incorrect.
That said, I suppose it needs some indication that Autofix can't fix it.
I'll add something.

**Comment by ghost** [comment]
Re-testing this in the pre-build since Creeper is afk.

So, I see that the error label has been changed to "ASPECT RATIO". I don't see this as any different than "DIMENSIONS", but I think both are fine. The progress bar output still doesn't say "Autofix failed". It does keep the texture flagged as invalid, so it won't install even if you click "Install valid" OR "Install" (this is good).

![autofix_aspect ratiopng](https://cloud.githubusercontent.com/assets/13645804/14411791/5643064a-ff07-11e5-881c-f475de525167.PNG)

The problem I see is that from the user's perspective, what they really care about is whether autofix fixed or didn't fix the texture. Whether or not it "completed" is a bit besides the point, which is what I think Creeper was getting at. If the green progress bar is filled and the message says "Autofix complete.", that gives the user the impression that it completed _successfully_. Which then makes it confusing, since the texture still has an error label.

I think we just need to be more explicit. @KFreon, I get your point that the process of autofix didn't "fail" --  it's that the texture isn't fixable in the first place. The tool is indeed working properly. However, from the user's perspective _it did fail_. The texture cannot be fixed and is not usable unless they fix it manually. It's important they understand this. So, how about having the Progress bar text say something like... "Unrepairable with Autofix. Requires manual fix."

This way, there's different debug text for Autofix actually _failing_, and cases when "repairing" a texture is beyond Autofix's capabilities. Of course, I'm assuming the tool has the ability to differentiate between the two.

**Comment by ghost** [comment]
Nice job with this @KFreon .

Now looks like this in the v3 prebuild:

![autofixar](https://cloud.githubusercontent.com/assets/13645804/14504015/b502feda-0167-11e6-9be2-bf5408a4f55a.PNG)

Issue is ready to close :)

**Comment by ghost** [comment]
For future reference, it's entirely possible this fix broke #212.
