### ISSUE TITLE
rev748, TPF Tools, Duplicates confusions

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#294]
Textures with the same name but different hashes seem to be considered as duplicates (those in italic), although they aren't. Thus, TPF/DDS only selects one of them when analysing, and you have to manually go through the list to check if it hasn't missed some.
![capture](https://cloud.githubusercontent.com/assets/12874678/14351846/e86561c2-fcd1-11e5-9620-e04fa264813f.PNG)

Testing files (ME2) : http://filebin.ca/2cwI40ayD0Qy (name dupes), http://filebin.ca/2cwNzUOXwjLg (hash dupes).

EDIT : Just noticed that hash duplicates don't seem to work as intended either : both duplicates are selected when analysing.
![capture](https://cloud.githubusercontent.com/assets/12874678/14352490/11892928-fcd5-11e5-8a72-ae4cab069b13.PNG)
The behaviour of hash and name duplicates should be reversed, right ?

**Comment by ghost** [comment]
I haven't downloaded the test files, since I haven't gotten to treebuilding yet, but in both screenshots the pair of textures look identical to each other. Are they indeed the same?

**Comment by starkgate** [comment]
There are 6 textures that have the name "bend_norm" in ME2. All of them have different hashes, all but one are DXT5, the other is DXT1. Sizes vary between 64x64 and 1024x1024.
Main thing is : different hashes, so the textures should definitely be considered different.

The bottom picture shows hash duplicates (ie 2+ textures with the same hash but a different name), these are identical.

**Comment by ghost** [comment]
Ok, so the top ones are definitely different, at least according to hashes. I'd think they should be installed separately and not compared to each other at all.

The bottom one is a tree duplicate, and at least in the past TPF Tools handled them correctly. I don't actually know if one or both are installed in this situation (do you?), but if anything has changed with them, it might be a result of the GUI formatting changes with the tab removal and the checkmarks, etc.

**Comment by starkgate** [comment]
Oh, yes, definitely caused by GUI. From my understanding, _hash_ duplicates should only need to be installed once, since it is the exact same texture, only mirrored with a different name. I may be wrong though.
In any case, they definitely do not need to be autofixed twice. Again, it's the same texture, so you can think of it as mirror : changes on one texture impact the other, inevitably.

**Comment by KFreon** [comment]
@CreeperLava The text in the first screenshot isn't italic, and TPFTools doesn't consider them duplicates, but the bit that Checks the textures after Analysis and Autofix was only checking names and not hashes.

Hash dupes are definitely both selected after analysis/autofix since they're technically different textures, otherwise I wouldn't split them. Now, at this stage, the toolset doesn't share data or anything i.e. they both need to be autofixed.
A poor method but it's just how it works for now.

Fixed the "duplicates" not staying checked after Analysis.

**Comment by ghost** [comment]
I'm not 100% clear what was supposed to be fixed with this in the prebuild but, the Bend_Norm textures still get unchecked after running autofix. To be clear, _they_ are not autofixed, but the Wall textures were.:

After Analyzing:
![dupes_analyze](https://cloud.githubusercontent.com/assets/13645804/14411966/a76333b6-ff0b-11e5-8b0c-ad913066400d.PNG)

After Autofixing:

![dupes_autofix](https://cloud.githubusercontent.com/assets/13645804/14411973/b10e4dce-ff0b-11e5-90c6-fa9d387a6fd0.PNG)

**Comment by starkgate** [comment]
What should be fixed is just that both ''duplicates'' should be selected after analysing. Which seems to be what happens, from your screenshot. They not staying selected after autofix is another issue.

**Comment by KFreon** [comment]
Ohhhh so everything that was selected after Analyse was still selected?
But everything after Autofix wasn't?

**Comment by ghost** [comment]
@KFreon -- Whatever I show above is exactly what happened. 

I'm not 100% familiar with the issue, since it's Creeper's report, which is why I figured showing the screenshots was the best way to go. I didn't manipulate the window contents in any way. Analyze > screencap, Autofix > screencap.

**Comment by KFreon** [comment]
Just trying to get the facts ma'am :)

It must have something to do with those textures not being included in the operation. I'll see what I can do.

**Comment by ghost** [comment]
Oh, now don't try to make me go all weak in the knees by channeling Kal'Reegar, now...

;)

**Comment by ghost** [comment]
@KFreon -- Uh, also see #296 , I think I just discovered something related to this issue while troubleshooting that one.

Duplicate hash detection is definitely not working properly. It seems to be tied to autofix somehow.

**Comment by ghost** [comment]
@KFreon -- TPF Tools is now hanging on matching hashes in the newest pre-build:

![hashmatch_hang](https://cloud.githubusercontent.com/assets/13645804/14465242/0d2a55ea-0087-11e6-9088-6ab6ffc1cc8c.PNG)

This should be pretty much instantaneous, but this at about 10 minutes.

After hard-quitting I tried loading a TPF that doesn't have any duplicates (since this seems to be the problem), just to see if the same thing happens. It does. FYI, this means I can't verify fixes for 292, 294, or 296 until this is fixed, so we need another pre-build :/

Also, see my recent response to issue #296, which I reopened, since it directly relates to how duplicates are detected.

**Comment by ghost** [comment]
@KFreon , @CreeperLava -- Here's how this looks in the latest prebuild:

Upon loading:
![dupes_loaded](https://cloud.githubusercontent.com/assets/13645804/14503163/9cd992be-0163-11e6-96ab-b0e6c572d848.PNG)

Post analyze:
![treenamedupes](https://cloud.githubusercontent.com/assets/13645804/14503107/63d9c858-0163-11e6-93fd-84e1cd70bc7c.PNG)

Post autofix:
![dupes_autofixb](https://cloud.githubusercontent.com/assets/13645804/14503115/6a32caec-0163-11e6-9d7b-b09c7b15da18.PNG)

Top 2 textures have different hashes and should be treated separately, which they are. The 3rd texture is a tree duplicate. Both are selected after both analyzing and autofixing.

This correct?

**Comment by starkgate** [comment]
What does the debug log say ? Does TPF Tools attempt to autofix both hash duplicates ?

**Comment by ghost** [comment]
@CreeperLava -- Debug looks like this for autofixing:

![autofix_dupes_details](https://cloud.githubusercontent.com/assets/13645804/14504102/2a6911aa-0168-11e6-95df-39104fe563c0.PNG)

**Comment by starkgate** [comment]
I'm not sure if it actually matters, but shouldn't TPF Tools only try to autofix one of the 2 hash duplicates ? Trying to fix the other one sounds like a waste of time. Then again, I don't know if trying to autofix something that has already been fixed takes any time anyways, so...

At least name duplicates seem to work properly now, thanks for fixing it !

**Comment by ghost** [comment]
@CreeperLava -- I don't think it matters and since it's not hurting anything, I say we leave it alone. The more things we change at this point the more room for those changes to feck up something else.

It's stable time. I say we close this issue, @KFreon.

---

Verified in r749 prebuild v3.

**Comment by KFreon** [comment]
That looks good to me too. Ooo stable, you evasive mistress. Your time is coming.
