### ISSUE TITLE
MIPS. Question

### ISSUE THREAD

**Issue by alvarome** [ME3Explorer/ME3Explorer#314]
Hi:

In advance, my apologies if this has been discussed before but it is new to me.

I have noticed the following a few interesting things regarding MIPS. I say things and not issues because I do not know if those are an issue at all.

I´ll try my best to post a vissual SBS that I´m sure will be easier to understand than my broken english! ;)

CASE A ____________________________________________________________________

I just wanted to install a hi-res texture in ME3 game to replace the folowing vanilla. Nothing unusual here. 64x64, 7 MIPS (that is, from my understanding, the 64x64 image plus 6 MIPS)

![image_01](https://cloud.githubusercontent.com/assets/17484308/14504006/aeb7f9f2-01aa-11e6-8ca7-9cbafeb68a50.PNG)

As I´m going to need this vanilla latter in this test, I extracted it using Texplorer, I loaded it into PS and saved it generating its MIPS. No secrets here.

Well... In TPF/DDS Tools I loaded the replacement hi res texture .dds. Once more, nothing unusual here: 1024x1024, 11 MIPS

![image_02](https://cloud.githubusercontent.com/assets/17484308/14504042/eea2cc72-01aa-11e6-8dc0-0ab66c000ff3.PNG)

I analysed it...

![image_03](https://cloud.githubusercontent.com/assets/17484308/14504075/21125e34-01ab-11e6-8a89-6ef5bd46092d.PNG)

And here you got something interesting. Vanilla texture has 7 MIPS but TPF/DDS Tools is reporting 11! Where do these come from?

EDIT --> notice there are two more bend_norm textures in ME3, sharing same name but different hash, size and/or format. Duplicated textures, not tree duplicates. You can see this at the first pic- 

That´s odd  but not a problem to continue with the install as the replacement texture has the same or higher number of MIPS than in tree.

This requeriment, the "equal or higher number of MIPS in the replacement texture" is the object of this post, BTW.

Please, notice from now on, this test is related to a not recommended use of the toolset.

We all know that, now, if I wanted to remove the installed hi-res texture, I have to go vanilla. Fresh  install or restoring a vanilla game backup.

But a temporary fix for lazy users - me first! ;) - could be to reinstall the vanilla texture.

And here is where the fun begins.

I loaded the vanilla texture in TPF/DDS tools:

![image_05](https://cloud.githubusercontent.com/assets/17484308/14504535/28f3050c-01ad-11e6-8876-f9cfe5564d56.PNG)

And I analysed it...

![image_06](https://cloud.githubusercontent.com/assets/17484308/14504551/3b0bb5fe-01ad-11e6-866a-013a718f03a2.PNG)

Oh, wait... the texture is valid when having less MIPS than expected? No way!

But I could install it. No problem at all.

![image_07](https://cloud.githubusercontent.com/assets/17484308/14504613/6ceabcf0-01ad-11e6-816c-837196ecefa8.PNG)

Of course, I launched the game and double checked the hi res texture was no longer used. So the vanilla installation was a success.

So, the toolset is working in an unexpected way here. 

And another question here... if the vanilla has only 7 MIPS... what about the other theoreticaly not replaced 4 MIPS that were supposed to be those from previously installed hi-res texture?

I ask before I have seen no side-effects in game at all but...

CASE B ____________________________________________________________________

This is another interesting test related to MIPS. 

For the first time, I was going to replace a 1 MIP (that is, no MIPS at all) vanilla texture with a hi-res one.

I loaded the hi-res texture in TPFDDS Tools.

![image_08](https://cloud.githubusercontent.com/assets/17484308/14505225/28fa7640-01b0-11e6-84f5-721e380dea6a.PNG)

And I analysed it...

![image_09](https://cloud.githubusercontent.com/assets/17484308/14505233/2f9a0d12-01b0-11e6-851c-f22524a7f19b.PNG)

Why the hi-res texture is not valid due MIPS? 

The replacement texture has equal or higher MIPS than the vanilla/tree one! No doubt, this is an unusual toolset behaviour I was not aware of.

That´s all.

Once more, thank you for your understanding in case this had been discussed before!

HTH!
Alvaro

**Comment by ghost** [comment]
@KFreon -- Lawl. This is exactly what I was afraid was going to happen if we starting listing mips numbers. Remember that conversation, lol?

@alvarome  -- 

CASE_A
1. You don't mention what version of the toolset you're using. You also don't mention if you built your current Texplorer tree with the same toolset version that you are currently using. Mip data is stored in the tree, and if you use trees built with previous revs and import them into a new rev, that data may not be accurate. This may be why Texplorer and TPF Tools are reporting different numbers of mips.
2. Downscaling from 1024 to 64 isn't a problem, _as long as you have the correct number of mips_, which you do (1024=11, 64=7). It's no different than upscaling; you must have the proper number of MIPs for the texture's size. As far as what happens to the 4 mips from the larger resolution texture, it doesn't really matter. They are still in the CustTextures0.tfc file, it's just that the game doesn't use them. I'd say the toolset is absolutely working as intended and expected.

CASE_B
The vanilla texture in this example has no mips. If you look in Texplorer, it says "Mips: No". Your replacement texture has mips and it shouldn't, which is why the toolset won't let you use it. This is also working as intended. You need to recreate this replacement texture _without mips_.

---

Here's all you need to worry about:
1. If Texplorer says "Mipmaps: Yes", let Photoshop/GIMP autogenerate the number of mips for you in your replacement texture. As long as the texture is 4K or lower, the mips number will _always_ be correct and it will install just fine.
2. If Texplorer says "Mipmaps: No", you don't need mipmaps. Ensure when you save the texture in PS/GIMP that you **do not** automatically generate mips.

**Comment by starkgate** [comment]
The toolset version he is using can be seen in the screenshots : 748.
- "Mip data is stored in the tree" I don't think so, if it was we would see that data in the CSV exports. I think MIP data is calculated on the fly by Texplorer and TPF Tools (with the 2^(n-1) formula for TPF Tools iirc).
- I wasn't aware the superfluous MIPs stayed in the tfc, that's odd. How would the game know he isn't supposed to use them ?
- I think you misunderstood what he is asking for with the no mips issue. The texture does have 1 MIP : itself. This is all coming down to wording and confusing descriptions, and I don't think there's much to be done here. Let's see what KFreon thinks.

I suppose what could be done (although probably not in the stable release, let's keep that as an option for WPF) :

In TPF Tools, replace Tree MIPs by Tree Size and add number of MIPs the texture _should_ have when you extrapolate the Tree Size.
eg if I have tree size 1024 and image size 4096, as long as the vanilla texture has MIPs, you can suppose that "MIPs the Image should have" = "Tree MIPs" + 2.

This would avoid the confusion of having seemingly incoherent MIP numbers, since you just have to compare "MIPs the Image should have" with Image MIPs ie "MIPs the Image does have".

**Comment by ghost** [comment]
@CreeperLava -- 
1. Kfreon said himself that mip data was stored in the tree. It actually led to a problem previously during testing that I experienced b/c I ported in an old tree. The CSV is not an accurate representation of all tree data, it only contains what K has specified. Texture size, for example, is also not in the CSV, but is certainly stored in the tree.
2. Nothing is ever removed from the TFC, textures are only ever added. What changes are the references in the PCC files.
3. No, I didn't misunderstand. Yes, there is 1 mip.  Again, this is exactly why I suggested no numbers in the first place. B/c there are no mipmap**s** for the texture. When a single mip exists, it isn't really referred to as a mipmap anymore. Mipmaps are by definition a _series_ of smaller replicates of a texture. When there are no replicates, there are -- by definition -- no mips. He's confused b/c he's trying to replace a texture without mips, with one that has mips. My TL;DR at the bottom is all he and anyone else needs to know when replacing a texture.

Either way, there is nothing to fix here. No problems at all, just user confusion.

**Comment by starkgate** [comment]
Well from what I can see in #300, MIP and dimensions are indeed not in the tree. Unless I missed something ?

**Comment by alvarome** [comment]
Hi:

Thanks a lot for the quick and prompt replies. Very informative, as always.

I´m also happy to know now that a Texplorer/PTFDDS tools info crosschecking  would be needed, at least for those few no mips textures. In any case, I already had removed all mips and installed the texture successfuly. But to see that the replacement texture was ok but flagged in toolset caught my attention.

As for downsizing... that was something new for me until I did it just a few days ago. Good to know too.

Regards!
Alvaro

**Comment by ghost** [comment]
@CreeperLava -- Well, K definitely does say so in that issue. I'm obviously remembering him conveying something else from a different issue, and I don't have time to track through all my issues right now to try to solve the mystery

I did experience a mip-related problem that stemmed from importing a tree, though. That I remember very clearly, and right now we don't know if his tree is an import or built on rev748 -- which may or may not shed light on the situation.

**Comment by ghost** [comment]
If the discrepancy isn't due to a tree built with a different rev, then it's possible that K is using different mip detection methods in the two tools. 

I was going to mention this initially, but thought the tree import was more likely and I didn't want to confuse the issue further. But, remember all that talk about "valid" vs "invalid" mips or whatever it was? And what "version" of the number K wanted to display? It's possible that Texplorer is showing one and TPF Tools is showing the other.

Short of that, the tree issue, or some weird user error I can't come up with any other ideas.

Actually, that's the texture I used earlier, so let me take a closer look now that I'm curious, lol.

**Comment by ghost** [comment]
Seems like user error (or an imported tree issue) to me.

Here's my rev 748 on my vanilla install with the same texture highlighted in Texplorer, and a replacement loaded and analyzed in TPF Tools:

![alvarome](https://cloud.githubusercontent.com/assets/13645804/14509619/16ae20c8-0182-11e6-8a05-1f50e2c95329.PNG)

Everything matches up as it should and Texplorer and TPF Tools show the exact same number of mips.

No problems, here.

**Comment by alvarome** [comment]
Oh, you beated me on that... i was building up a fresh 748 tree because I was unsure if I used a native tree or a 747 one.

Same results here, BTW.

No doubt you may be tired of these questions but, once more, thank you for your time and your detailed replies. 

Regards!
Alvaro

**Comment by KFreon** [comment]
I'm on my phone and at work so forgive me if I forget to answer a question.
- Most texture data is NOT stored in the tree because if it was, the tree would need updating all the time. Texplorer uses the First listed file of a texture to populate the textures current condition.
- I consider 1 mip to be what you call no mips. Technically a single image probably should be called no mips, but I call it 1 or single mip.
- all this will be fixed in wpf as gift and I talked about, texplorer will say Yes(mip count) or no(1).
- since a texture is being replaced, all mips must be available in the replacing image. Hence a replacing image will always have equal or more mips then vanilla.

Hope I answered anything.
