### ISSUE TITLE
rev750 RELEASE Version Texplorer bug

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#339]
This is a bug specific to the Release version, I can't reproduce it in the Debug one. It also seems specific to ME1 and ME2.

Double-clicking a texture in Texplorer to get the preview, throws this error :
![decompression failed](https://cloud.githubusercontent.com/assets/12874678/14760733/10db4546-094c-11e6-8086-aa85da00c9d1.png)

Log [here](https://github.com/ME3Explorer/ME3Explorer/files/232893/decom.txt).

**Comment by alvarome** [comment]
I also wanted to report I´m unable to buid up ME1 /ME2 trees with this release version. I have not tested using debug one!

ME3 tree build is OK!

ME1 / ME2 tree progress is superfast (not a good thing, I´m afraid) and, suddenly, a window opens reporting a bunch of not scanned files, giving me  two choices: "ok" and "save". 

If I click "save" that opens a "save as" were no matter I put a file name or a folder name, I´m unable to save nothing at all. Something wrong here from my side for sure because that´s the very first time I see this.

No app exception windows. No crashes.

Restoring vanilla backups to double check and take some screenshots.

HTH!
Alvaro

EDIT: ME1 tree: Debug log reports LZO decompression failed in a bunch of .SMF files. So perhaps a problem at my end... but I did a tree buid few days ago using 749 and everything was fine -?-

EDIT: ME2 tree: Debug reports System.Exception: LZO decompression failed

**Comment by KFreon** [comment]
Well there you go. Guess Release still doesn't work.
I'll take it down.
