### ISSUE TITLE
Beta: Remove "Decompressor"

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#351]
I have been looking through the code and have seen a tool named Decompressor. Upon opening it, there is _literally_ no information about what this tool does. Digging a little into the code indicates this literally calls the Decompress.exe file in the exec folder and nothing more. This Decompress.exe file decompresses PCC files for the alt-save feature of PCCEditor2 (not sure if that is even available in menus anymore), but it it seems widely used around the toolset in the code behind the scenes. This snippet in Alt-Save loads the form, calls Decompress.exe, and closes the form. This has a lot of overhead, and serves no real purpose. (My command line args kind of do this, but without major modifications is why I just go through the GUI instead).

I have a commit prepped that entirely removes this tool and takes its relevant code (Runshell( Decompress.exe, pccfile)) and moves it into the PCCObject alt-save method, which is the only actual reference. The tool itself is a half-duplicate of PCCRepacker, as that can decompress PCCs as well as compress them.

Wanted some thoughts before I added this to my pull request.

**Comment by SirCxyrtyx** [comment]
Seems safe to do, since it's used nowhere else.

**Comment by Mgamerz** [comment]
I'll include it once I do finish testing my last commit more thoroughly.
Then it should be ready to pull.

**Comment by ghost** [comment]
Are we sure nobody uses this for anything?

Removing tools via Git discussion feels a bit sketchy. I've pointed this out before, but the problem is that most folks aren't reading these issues. In cases like this, I think it's worth throwing up a forum thread in the toolset dev section first, just to make sure nobody uses it for anything. I understand that it takes more time, but sometimes modders use things, and we just don't know about it.

This is similar to the process I went through when writing the wiki articles for the User Tools. I posted a thread for the tool, clarified functionality, often made some UI changes, and then in certain situations we discussed if the tool could be removed.

**Comment by SirCxyrtyx** [comment]
I'd agree for most tools, but since this tool just replicates some of functionality of the PCC Repacker tool, it's safe to remove. If anyone was using it, they shouldn't have been. The PCC Repacker is superior, not only in that it does more, but in that we control the code.

**Comment by ghost** [comment]
@SirCxyrtyx -- Ah, that's very good to know. Makes sense.

I didn't understand the functionality of all the User Tools until making the wiki articles, so it's the same with the Dev Tools. Of course I understand the ones I use, but if I don't use it, then I definitely am not at all familiar with it's functionality. Thanks for clarifying :)
