### ISSUE TITLE
Add a warning if Texmod.exe can't be detected (anti-virus removed it)

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#369]
Apparently ME3Explorer doesn't output any error if the Texmod.exe can't be detected (which happens when antivirus remove it). This can lead to an error where textures can't be loaded in TPF Tools, and no warning is given. Very hard to troubleshoot unless you saw the error before. A user sent me these screenshots :
![wqccs6b](https://cloud.githubusercontent.com/assets/12874678/15464001/13144496-20cd-11e6-9f19-6c33655772d3.png)
![5c5htku](https://cloud.githubusercontent.com/assets/12874678/15464000/131174c8-20cd-11e6-80be-af0ab7f236f8.png)

Just adding a condition for the exe would be enough, and output a warning to fix the problem (redownload ME3Explorer, deactivate antivirus and transfer trees). The antivirus that removed the exe was avg free edition, but there are probably others that have a similar problem.

**Comment by ghost** [comment]
Creeper, you'll probably want to submit this to K's fork. I'm pretty sure he plans on removing Texmod in the re-write, but it couldn't hurt to give him a heads up.

I don't see us being able to do this for the main project, as we won't be making any further modifications to the code for his tools.

As a band-aid, we could certainly incorporate the issue into the wiki's FAQ for TPF Tools. That way folks aren't surprised at the AV false-positive and know how to deal with it.

**Comment by SirCxyrtyx** [comment]
TPFTools doesn't use TexMod to load tpfs though. As far as I can tell, the only time Texmod.exe is used is when creating a tpf.

**Comment by starkgate** [comment]
Well deactivating the antivirus/redownloading apparently fixed the issue, so there must still be some weird stuff going on when the exe is missing.

Can't we just add this little warning ? This issue probably comes up regularly, but since I only heard of it once or twice, I must guess most people just abandoned. It would help greatly to incorporate the warning in the tools. Shouldn't break anything, either, you just need a conditional.
If not possible, then I would definitely appreciate an entry in the wiki.

KFreon's branch is the WPFMerger, right ?

**Comment by ghost** [comment]
> Can't we just add this little warning ? This issue probably comes up regularly, but since I only heard of it once or twice, I must guess most people just abandoned. It would help greatly to incorporate the warning in the tools. Shouldn't break anything, either, you just need a conditional. If not possible, then I would definitely appreciate an entry in the wiki.

K, Sir, and I all agreed that after the stable the best way to move forward with K's tools would be that see no further modifications and be in archival state. I'll leave it up to Sir, though, as while K is on break, Sir is lead dev in the interim. If Texmod.exe is only used when generating TPFs, then it's not going to be a problem for the vast majority of users, as they will only be installing TPFs. My instinct says we shouldn't touch it. Archival is archival, and any changes in the code for K's tools tends to have unintended effects. Thus, even the smallest change needs to be tested.

Either way, it should _definitely_ be in the FAQ for the wiki. That's a notable oversight, so glad you mentioned it, regardless.

> KFreon's branch is the WPFMerger, right ?

No, that doesn't sound right. Here's his:

https://github.com/KFreon/KFreons-ME3Explorer

**Comment by SirCxyrtyx** [comment]
I'd be amenable to sticking in a warning _if_ I thought that a lack of Texmod was really the issue. There's only one place in the code where Texmod.exe is called, and if it's not found, a messagebox pops up to inform the user. 

Also, I deleted Texmod from my ME3Explorer installation, opened up TPFTools, and loaded a TPF with no problems. 

I'm willing to believe the anti-virus screwed something up, but if so, it wasn't something as simple as deleting texmod.

**Comment by starkgate** [comment]
Good point Sir, thanks for testing.If Texmod wasn't the issue, I'd be curious to know which file was removed (if any), that prevented ME3Explorer from working. It may not even be possible to prevent or even warn if the antivirus is blocking the process itself. Well, I suppose this issue can be closed then. I'll ask the user to do some testing to try and figure out if another file was removed.

Could having a sort of integrity check of ME3Explorer at first launch help ?

**Comment by ghost** [comment]
@CreeperLava , @SirCxyrtyx -- I was thinking about this overnight, and other files are definitely an issue.

When I have to upload stables to Nexus, it's not just the Texmod.exe that gets flagged. That's the most common one, but there are other files that flag false-positives.

Integrity check isn't a bad idea. I think the best way to prevent the problem in the first place is to build an AV step into the Getting Started guide, which I'll do this morning. Due to the false positives, folks should do one of two things: disable their AV just prior to the toolset download, OR ensure that they put the AV under manual control for when it encounters a suspicious file. It would also be exceedingly helpful if they submit the false positive to their AV; usually there's a button for that as the problem file pops up.

Btw, it's possible to do the same thing for the Nexus AV report results. You just click on the little yellow icon next to the file and it bring up the AV report. From there, you can mark the file as "okay". The more folks we can get to do this, the better. It takes 10 false positives to trigger the file lock down and we usually trigger 11-15. If enough folks report the files as okay, we can get that number down below the threshold, so I won't have to deal with the file getting locked down on each update. Grrr.

**Comment by ghost** [comment]
FYI, I've built the step for the AV into the setup guide.

I didn't build it into any FAQs so far as I don't think the situation is consistent enough across users for us to be able to write up a logical scenario of problem/fix.

**Comment by KFreon** [comment]
I'm guessing this can be closed now since Texmod is no longer included in the toolset?

**Comment by SirCxyrtyx** [comment]
Indeed it can. :tada:

**Comment by ghost** [comment]
Yaaaaaay.

Seriously, uploading stables to Nexus just got about 12x easier.

For you, @KFreon :beer:
