### ISSUE TITLE
Package Editor exports start at 0 instead of 1... issue?

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#370]
The exports list in package editor start at index 0. However, values in interpreter are indexed starting at 1. This leads to a ton of confusion and I'm not sure if it's correct behavior or an oversight we've had for some time.

**Comment by SirCxyrtyx** [comment]
UE3 indexes the exports starting at 1, and the imports starting at -1, with 0 meaning Class. So one signed int can represent any export or import. These are the values displayed in the interpreter.

When ME3Explorer reads the PCC, it puts all the exports in one array and the imports in another. So the number shown in the export list is just the index in that array. I'm pretty sure this is a prime example of an implementation detail that should never have been exposed to the user. Fixing it at this point would be a huge task though, as it's like that all over the toolset, not just in the PackEd. It would also probably be very confusing to all the users who are used to it by now.

**Comment by Mgamerz** [comment]
Only reason I brought it up is when I am looking up a value to put in interpreter (in this case I am making geth prime use pulse rifle instead of his gethprimerifle), the indexes are all off by 1 in the exports list which really irritating. When I look in interpreter of the gun I want to use to find values, its the right values, but its sooooooo easy to mix them up and I end up wasting a lot of time fixing them.

**Comment by ghost** [comment]
I was going to bring this up during the re-write, @SirCxyrtyx. 

I don't think it's something we want to address yet, but when it comes to overhauling the interface and functionality of Package Editor with the new GUI implementation, I think we're going to want to address it. 

Over the past 6 months we've added in a bunch of new editable/informational fields in Package Editor, and it has indeed gotten very confusing. These types of changes are the types that I'd like to see us discuss more on the forums in those new dev threads, as while more information seems like it should be a no-brainer, it isn't always.

This problem is why I recently got very confused during a exchange about NPC editing and archetypes. I think You and Kinko were in on this conversion. There's now _multiple_ areas in Package Editor where sometimes it's +1 and sometimes it isn't. Trying to keep them all straight is getting harder and it's very, very easy to forget and make a mistake. Before all the new fields were added we didn't have the problem as much. Generally it was all just +1.

If we can start _thinking_ right now about how we could deal with this, that would be a good thing. But, I don't think anything needs to happen until we overhaul the Package Editor GUI.
