### ISSUE TITLE
2.0.5: Package Editor save as is slightly confusing (3 options, all diff, but really only 2)

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#371]
In package editor there are now 3 save buttons - save, save as (append), and save by reconstructing. This is kind of confusing as not everyone may know what the difference between append and normal save is (pretty sure there isn't, its literally just save as right? Now that alt save is gone), and save by reconstructing doesn't work in dlc. If a DLC pcc is loaded, this option should be greyed out or invisible.

**Comment by SirCxyrtyx** [comment]
"Save" will do an append save if possible, and a reconstruction save if not (when cloning or importing has occured)
Append is the normal save method, yeah. 
I changed "Save As" to "Save As (append)" both to contrast it with "Save As (reconstruct)" and to give more information as to what it was doing.

I'd forgotten that PackEd could load things from inside an SFAR. Reconstructed pccs don't work in an SFAR? Why would that be?

**Comment by Mgamerz** [comment]
You can't reconstruct a DLC file if it has the seekfreeshadercache export
right? It breaks it. When I was working in pre 2.0.5 I noticed your save
code would switch between reconstruct for files without that (which are
basegame) and ones that do (dlc ones). Seekfreeshader cache, AFAIK, it in almost all DLC pccs, if what I recall from the forum thread was right. It's why ME3Creator and DLC PCCs files were a problem for a while.

Kinkojiro has more info on the forums and here. Otherwise we would just use save (reconstruct) always.

**Comment by SirCxyrtyx** [comment]
You can reconstruct it if you remove all the binary data from the SeekFreeShaderCache export and change its class to "Package". That's why I checked to see if it it had the class "ShaderCache". If you click the "Save As (reconstruct)" button (or try to clone or import) when there is a SeekFreeShaderCache with class ShaderCache, it won't let you do it, and offers to direct you to the forum thread where Kinkojiro explains how remove the SeekFreeShaderCache (and when it's okay to do so).

Btw, isn't this backwards? https://github.com/Mgamerz/ME3-GUI-Transplanter/blob/master/ME3%20GUI%20Transplanter/TransplanterLib/TransplanterLib.cs#L190
(and I feel I ought to mention that reconstruction save does not "take a while", it's actually almost instantaneous :)

**Comment by Mgamerz** [comment]
Haha yep, good catch. I'll post a fix and update my users builds. 😉 That bug is only present in the single SWF replace which the main Mod Manager compatibility generator doesn't use, but I've fixed it regardless.

And yes it is very speedy, I like how fast it is. It also cuts out the file size buildup over time the old save methods used. The "may take a while" is just how the other was worded in the past.

**Comment by SirCxyrtyx** [comment]
Just figured out why the append save is so incredibly slow. 

```
ExportEntry lastExport = Exports.Find(export => export.DataOffset == Exports.Max(maxExport => maxExport.DataOffset));
```

That's O(n^2) 😱. And there's no reason for it to be.
Here's what I changed that to in 3e91a111ead70eee0482906d61ae4a210292bbee:

```
int max = Exports.Max(maxExport => maxExport.DataOffset);
ExportEntry lastExport = Exports.Find(export => export.DataOffset == max);
```

Now it's O(2n). Saving even the biggest of pccs should take less than a second now.

**Comment by Mgamerz** [comment]
Does this apply to decompressing pccs as well? Decompressing sfxgame pcc
literally takes minutes. It's brutal. I know there is decompress.exe and
also just a savetofile method.

**Comment by SirCxyrtyx** [comment]
As of 2.0.5 decompress.exe has been removed, and all decompressing is done by saving the pcc with the reconstruction method (files with a SeekFreeShaderCache wouldn't ever be compressed). So it should be pretty speedy.

**Comment by Mgamerz** [comment]
Nice.

**Comment by Mgamerz** [comment]
Question - I have a large set of binary patches that only can apply to a
file of a specific size (mixins). They essentially just patch a value or
two, and you can stack as many of these as you want in a modular fashion.
They only work on decompressed pccs - does the reconstruction method of a
vanilla, compressed PCC change the file vs using the old decompress method?
I don't think it used the exe in older versions, but I can't be sure.

Edit: I checked on a few files, the filesize is the same. However, some bytes in the header were different. Not sure which ones or if it actually matters.

**Comment by Mgamerz** [comment]
You're still checking that it doesn't contain seekfreeshadercache right? Users can manually compress pcc files from a dlc. Saves disk space for end users.

**Comment by SirCxyrtyx** [comment]
Can you compress a file if it has a SeekFreeShaderCache? Wouldn't that break it?

**Comment by Mgamerz** [comment]
Files are decompressed by the engine as they are loaded into main memory.
Same as a zip file or 7z for example. Compressed PCCs simply use disk less space (not much performance loss as LZMA/LZX is very fast to decompress).

However, distributing a mod with compressed PCCs uses more bandwidth, as you distribute it in something like 7z. 7z has better compression than pcc's natively (obviously game can't read 7z), so compressing an archive of uncompressed pccs will find more duplicate data to compress vs a single pcc compressing data in its blocks. 7z won't be able to compress compressed pcc's anywhere near the efficiently that it can with uncompressed.

**Comment by SirCxyrtyx** [comment]
I just remembered why I was so confident that files with SeekFreeShaderCaches wouldn't be compressed: PCCs saved using the append method can't be compressed. So if someone has edited it, they won't have been able to compress it, and if someone compressed a vanilla dlc pcc for some reason, then it would be fine since a reconstruction save performed on an un-modded file _should_ produce an identical file.

**Comment by Mgamerz** [comment]
Wouldn't that imply any PCCs edited before 2.0.5 wouldn't have been compressable? Both save methods would append if the export size was expanded (one would always append). I definitely have seen compressed pcc's being shipped in people's custom dlc mods. When I was testing the saving code I had my pcc's accidentally automatically compress and the game still loaded the file fine.

Should it still check edge case in case there is a seekfreeshadercache for some reason?

Also I was testing the old vs new decompress (saves) and the file is almost 100% the same. There are several bytes in the header of the pcc that are modified.

**Comment by SirCxyrtyx** [comment]
I could swear I remember someone saying that append-saved files couldn't be compressed. Well, I can add in a check just in case.

**Comment by Kinkojiro** [comment]
Append save files cannot be compressed.  Before 2.0.5 you used to have to save in package ed, reopen and save in me3creator then compress.  No dlc files are compressed afaik.

If I remember right it wouldn't break anything it just wouldn't work.

**Comment by Mgamerz** [comment]
They aren't compressed by default (they are compressed by their sfar
containers)

**Comment by ghost** [comment]
> I'd forgotten that PackEd could load things from inside an SFAR. Reconstructed pccs don't work in an SFAR? Why would that be?

@SirCxyrtyx -- I don't know anything about re-compressing/reconstructing PCCs, etc, but I think it's probably safe to remove the "Load/Save into SFAR" options. I don't remember when they were added, but they've been in the toolset a long time. I suspect they were implemented only to save the step of having to go through DLCEd2 to extract/replace the PCCs prior to and post-editing. It's also possible they pre-date DLC Ed2, and are therefore, redundant.

At this point, I'd say both are probably deprecated. Most modders will have their SFARs unpacked. Even if they don't, they'll likely be using the edited file as part of a DLC mod, so there's no need to pack it back in teh SFAR, anyway. Finally, if their DLC is still -- in the rare case -- packed, then the same functions can be completed via DLC Ed 2.

Since it simplifies the situation in Package Editor, I'd say they are okay to remove. It would be better to have all SFAR-related editing features completely separate and only inside the SFAR-specific tools.

**Comment by Mgamerz** [comment]
I think it is still useful. There are times where I don't want to unpack
dlc (say I'm on a vm - other modders are on VMs too, iirc deager) and don't
want to use a huge amount of space. Save into dlc though isn't as useful
though.

**Comment by ghost** [comment]
That seems like the appropriate time to use SFAREd2/Basic Editor to extract a file or two, and then load it up into PackEd, manually. The fact that the same functionality exists there was part of my point. Having it integrated into PackEd saves a step, but it's not going to be used very much anymore. Better to strip out all SFAR-related features, leaving them confined to the tools that are named for them. Plus, it simplifies PackEd and makes it less confusing.

We don't have "Load from SFAR" in any other tool. Not in CND Editor, Sequence Editor, Codex Editor, ME3Creator, etc, I don't see why it should be in PackEd. If we don't remove it now, then it's likely something we'll revisit in the GUI overhaul when every feature for every tool is challenged.

**Comment by SirCxyrtyx** [comment]
Agreed. SFAR handling should be confined to the two SFAR tools. I'll strip those two options from the menu.

**Comment by SirCxyrtyx** [comment]
As of 2.0.11, the user no longer gets to choose the save method, so the only options are "Save" and "Save As". ME3Explorer decides what save method is appropriate.

**Comment by ghost** [comment]
Yay. Love this.
