### ISSUE TITLE
Allow editing of export class type

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#375]
A few months ago I added the ability in PCC Editor to see the class of an export directly in the list. Here's a picture.

![image](https://cloud.githubusercontent.com/assets/2738836/15624598/f1757cfe-2448-11e6-9bc6-b6183e952280.png)

I have found there is no way to directly edit this value, and could be useful if you want to upcast an object (or change it... probably would break stuff but thats up to the user). Items in [] are exports in this file, () are imports. IIRC these are the last 4 bytes of an export. I noticed when I manually edited this value and saved hex changes, the type does not update in the exports list.

Also, the meta data editor is really slow to load, always. Not sure why.

**Comment by ghost** [comment]
If I'm understanding you correctly, ME3Creator is the better tool for editing classes.

**Comment by Mgamerz** [comment]
I am changing an object class type, not editing a class itself.

**Comment by SirCxyrtyx** [comment]
To be more specific, what you're talking about is editing the expected type of an ObjectProperty or StructProperty in a class or function definition. I don't see the benefit of adding a box to edit this value honestly. It's a value that's specific to only a very few exports, editing it is not something that will need to be done often, and if it does you can just edit it with the hex editor. The exports list isn't reloaded after hex changes are made  since this value is the only scenario in which editing the hex would change what was displayed there. If you want to check that the value you inputted is correct, just switch to imports view and back.

**Comment by Mgamerz** [comment]
Okay. I can deal with that.
