### ISSUE TITLE
Texplorer doesn't show all UI elements

### ISSUE THREAD

**Issue by Lucatir** [ME3Explorer/ME3Explorer#392]
This happens in the latest stable version and latest unstable version at the time of writing.

Some UI elements are out of bounds of the window. Window cannot be stretched anymore horizontally.

![Image](http://i66.tinypic.com/2lc04s6.png)

What should be visible is all the threes and games + plus the button for modifying a certain game in the series I think?

I use high display dpi scaling and normally you can disable high dpi scaling in a programs compatibility setting, but texplorer does not have it's own individual executable and making that modification to me3explorer binary itself does not give the effect to texplorer.

I was able to use a workaround by disabling high dpi scaling in Windows by setting it at 100%.

Edit: When I set the scaling back to 150%, the ui element is still visible.

**Comment by ghost** [comment]
This is a known problem with DPI scaling and the toolset. Winforms doesn't handle this well.

We're currently in the process of transitioning to WPF, which should handle this better, but it'll likely be awhile before we get to Texplorer. In addition, Kfreon's tools are in archival state and will see minimal modifications. Only those absolutely necessary to preserve existing functionality under WPF.

I'm going to close this issue, since we're already aware of the issue and it's something relevant to the entire toolset. It's not something that will be fixed, specifically, but will be addressed with the transition to WPF.

**Comment by xXxSoULMaNxXx** [comment]
I am having this issue now.  I need help as it makes ME3Explorer not usable.   I cannot switch from ME3 to ME2 and cannot build a tree.
