### ISSUE TITLE
Plot Editor: Search Feature

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#417]
I begged TankMaster for this feature for several months, but he never got around to implementing it.

There is no way to search the Plot Editor. You cannot search for a specific plot bool, integer, codex page, section, etc. To look up a plot ID when I don't know what state event sets it, I literally have to scroll up and down the list clicking on each event and bool to try to zero in on it. Most of the time, this works, since they are roughly in order. Other times this doesn't work b/c of the "roughly" part.

Making the contents of each main list within each tab searchable would be aweeeeesome.

**Comment by SirCxyrtyx** [comment]
To start, I can make it easier to see what a plot bool, int, or float is without clicking on it:
![image](https://cloud.githubusercontent.com/assets/5533111/18569135/af64c680-7b55-11e6-807d-dbf00384be0e.png)

There's a fourth tab in the code called "Find Object Usages" that looks like it was the beginning of a search feature. I hid it because it had no functionality. I'll see what I can do about completing it.

**Comment by ghost** [comment]
> To start, I can make it easier to see what a plot bool, int, or float is without clicking on it,

That's fantastic. TankMaster originally had something like that in place, and then later on required clicking it... which is when I went back to an old version, lol.

**Comment by ghost** [comment]
Holy crap that was fast. TankMaster seemed to think it was going to be a real pain to implement.

Nice work :)
