### ISSUE TITLE
2.0.14 Bug: Texplorer and modded DLC files

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#425]
Not sure whether this is a KFreon issue or a SirC (probably both).  It might be a major headache, but at least we should warn people.

I am trying to add textures to a modded DLC file (i.e. it has a shadercache, and I have cloned a few objects).

Whenever I edit the textures via texplorer it corrupts the file completely.  Sometimes it crashes part way through the texplorer process.

There might be an incompatibility between the new DLC save method and Texplorer.

**Comment by KFreon** [comment]
I seem to recall something like this ages ago where accessing DLC textures directly "worked" but failed in game. Never did figure out what was causing it.
Wonder if it's the same thing as this.

**Comment by ghost** [comment]
This is a significant problem. Hopefully, @SirCxyrtyx can take a look soon, Kinko, I know you're trying to get EGM out.

**Comment by SirCxyrtyx** [comment]
> There might be an incompatibility between the new DLC save method and Texplorer.

That's probably it. I'll get on this ASAP.

**Comment by SirCxyrtyx** [comment]
It occurs to me that if the problem _is_ an incompatibility with the new save method, then we're going to have to put out a new stable before the EGM release, else people won't be able to apply texture mods on top of it.

**Comment by ghost** [comment]
Oh snap. Was hoping we'd be able to give the GUI a bit more of a test first.

Good news is that no Texmod.exe means we should no longer hit the minimum of 10 (false) AV report flags, lol.

**Comment by Kinkojiro** [comment]
Just to be clear.  The files always build in the tree correctly, it is only when you try to add textures that it falls over.

Here is a couple of examples (clean versions), one with just a single cloned sequence object, the second with cloned textures.  I also put in the test texture.  https://dl.dropboxusercontent.com/u/64867763/MapMod/TEXPLORER_bug_originals.7z

Exact findings:
- Tree building ok.
- Replacing the texture via Texplorer sometimes works sometimes it freezes. 
- After texplorer completes the file cannot be opened by package editor or by texplorer. "Error: Exception of type 'System.OutofMemoryException' was thrown."
- They crash the game.

Not sure whether this is related but I just noticed that 2.0.14 Package Editor cannot open the (pre-texture versions either).  Weirdly the cloning was done in Sequence editor, which opens them without problem, and actually package editor can open them via Sequence editor fine as well... which is a bit weird.

**Comment by SirCxyrtyx** [comment]
Texplorer's save method is appending changed export data and the names list to the "end", but it it was defining "end" as the end of the data for the export with the largest data offset, which, for the new save method means that it was trampling all over the export table. I've redefined "end" to actually be the end of the file, and everything seems to be working fine with the files Kinkojiro gave me after replacing the Miranda texture.

**Comment by Kinkojiro** [comment]
Thanks very much.  This is good news, I was worried it was going to be a difficult fix.

Is there a chance this gets rolled out as a new stable before Oct 2nd?

**Comment by ghost** [comment]
I guess we'll have to. It's a bit unfortunate, though, I'm not sure if ModMaker has been tested at all in the new GUI. I think TPF Tools has been tested a bit. I wasn't yet convinced that we didn't have new bugs in some of the lesser-used tools.

@SirCxyrtyx -- A new stable also means that I have a bunch of wiki work to do that wasn't on my schedule:
- Revamp the TOC and article categories to correspond to the new GUI, since the wiki layout specifically follows the GUI to make it easier for users
- Write a v2.0 vs v3.0 comparison article to help orient users
- Re-write the Getting Started Guide to correspond to the changes in GUI and initial setup

I'd guess about 10 hours of work. Maybe more. 

Also:
- We'll also need a solid answer from K on whether trees made with v2.0 will work with v3.0. 
- We may need some small changes to the Git website page. These shouldn't be a big deal.
- Nexus page will need obvious adjustments. I'll take some screenshots of the new GUI.

FYI, considering the drastic visual overhaul, I sort of assumed once we did roll the new GUI into the stable, that it would be v3.0 but I'm good with whatever.

**Comment by KFreon** [comment]
Since I haven't changed anything in the main branch, trees are unchanged.
With my UI, I'll have some conversion code from old to new trees.
