### ISSUE TITLE
3.0 - Initial Setup window

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#439]
I went through the Initial Setup, set the paths, unpacked the DLCs, made my trees, etc. The problem is that every time I run ME3Explorer, the Initial Setup window pops up again. I have to click "Paths OK" for the setup to figure out that everything is already done and to be able to run ME3Explorer.

This is probably caused by the fact that I had crashes when unpacking DLCs with 3.0, and had to do this initial setup with an older version of ME3Explorer. However, shouldn't ME3Explorer be able to detect whether or not it needs to run through the initial setup ?
![me3explorer_2016-10-16_14-49-15](https://cloud.githubusercontent.com/assets/12874678/19418270/dda82496-93c0-11e6-8c85-878bdd8fa05e.png)

**Comment by ghost** [comment]
It does have detection methods built in.

Are there PCConsoleTOC.bin files in all your DLC root folders?

**Comment by SirCxyrtyx** [comment]
Copying a previous comment:
Initial setup will trigger under two conditions if the disable initial setup option isn't enabled:
- The toolset cannot find the ME3 Executable
- Any directory in ME3's BIOGame/DLC/ other than "_metadata" does not have a file that's name ends with "pcconsoletoc.bin" (case insensitive)

Are either of those not true?

**Comment by starkgate** [comment]
The toolset should be able to find the ME3 executable. There is no PCConsoleTOC.bin file in the DLC_UPD_Patch01 and Patch02. Not sure if that's normal ? Afaik there are no textures in these "DLCs", so no need for a TOC bin ?

**Comment by ghost** [comment]
> The toolset should be able to find the ME3 executable. There is no PCConsoleTOC.bin file in the DLC_UPD_Patch01 and Patch02. Not sure if that's normal ? Afaik there are no textures in these "DLCs", so no need for a TOC bin ?

Not normal.

The TOC isn't a "texture thing". The game won't load the main Cooked or any DLC that doesn't have a TOC. Each TOC inventory has to match the base game/DLC it's for, or the game won't load. So, whether or not there are textures in the patch DLCs is irrelevant. A TOC must _always_ be present.

In this case, the toolset thinks those DLC are improperly extracted b/c there is no TOC. What happens if you allow the extraction? It should extract/create them, which should solve your problem.

**Comment by starkgate** [comment]
Interesting. I didn't uncheck any DLCs when extracting, but I also extracted them with 2.0.8, so the issue may not be caused by 3.0 itself. I'm reinstalling everything, I'll test it again once the fix for the DLC extraction crash is out.

**Comment by ghost** [comment]
> I didn't uncheck any DLCs when extracting, but I also extracted them with 2.0.8, so the issue may not be caused by 3.0 itself.

From memory, extraction was an all or nothing thing with v2.0 (including some previous betas). This was when extraction was moved outside Texplorer to Initial setup. Once that was done, extraction was a blanket operation -- all or nothing -- no more choice in which DLC to extract. If yours were extracted with v2.0.8 then that shouldn't be your problem.

In r653, the stable previous to v2.0, DLC extraction was still done via Texplorer, improperly, leaving TOCs  inside the SFAR. This is what created all the issues with texture installation, TOCing, BW DLC, and DLC mods. This is why recent versions of the toolset use detection for TOC in the DLC root as a test for proper extraction.

**Comment by GreatEmerald** [comment]
I get this problem as well... but I don't have ME3 installed to begin with. I'm using the tool for ME2 modding, not ME3. Looks like the side-effect of that is that the first setup screen keeps popping up...

**Comment by ghost** [comment]
@GreatEmerald -- Let me tag @SirCxyrtyx, as I'm not sure we ever discussed an Initial Setup scenario where ME3 wouldn't be present. As stated above, you're failing the check for locating the ME3 executable, since you don't have it installed.

For now, just disable the wizard in the Advanced Settings.

---

@SirCxyrtyx - I'm assuming the executable check is related to the pathing detection? Also, why not check for all executables? Obviously only ME3 needs DLC extraction, but one thing we never really discussed is if we wanted the wizard to appear for situations where ME3 isn't present, just so that pathing could be actively verified by the user.

Another thing we need to keep in mind is the intent that folks should be able to use the toolset without any game installed. This seems strange and will be the exception to the rule, but it's nice for modding, since it allows you to load up the toolset and some files onto maybe a tablet or laptop to do work when on the move. Should we just let folks know that in these situations they'll need to disable the wizard manually?

**Comment by SirCxyrtyx** [comment]
Executable check is actually there for DLC extraction purposes. If it can't find the exe, then it can't determine whether they're unpacked. Basically, the toolset is asking, "Are the ME3 DLCs all unpacked?", and there are three possible answers to that: yes, no, and unknown. Only if the answer is yes will it skip the initial setup menu.

This is of course a problem if someone doesn't have ME3 installed, because the answer will always be unknown. Perhaps it should be set up so the dialog opens the first time the toolset is opened, and then after that, only if the answer to the DLC extraction question is no. That way it won't keep bugging people who don't have ME3 installed.

**Comment by ghost** [comment]
> Perhaps it should be set up so the dialog opens the first time the toolset is opened, and then after that, only if the answer to the DLC extraction question is no. That way it won't keep bugging people who don't have ME3 installed.

That would probably work :)

**Comment by KFreon** [comment]
Might I suggest checking the me3 directory class variables to see if it's installed as a second check?
So if the variables are blank, the dialogue isn't triggered?

**Comment by ghost** [comment]
> Might I suggest checking the me3 directory class variables to see if it's installed as a second check?
> So if the variables are blank, the dialogue isn't triggered?

I think it's still a good idea to trigger it so users can verify pathing, regardless of game (or if no games are installed). It's a small thing to have them do and saves headaches in the long run by ensuring the toolset is using the correct locations. Also, it makes things clearer on the wiki if Initial Setup always occurs, regardless of which combination of games, no games, etc.

**Comment by KFreon** [comment]
Fair point. I suppose the initial also deals with pathing. I forgot about that.
