### ISSUE TITLE
v.3.0 - Texplorer - UI Not Loading, Cannot switch from ME3 to ME2 to Build Tree

### ISSUE THREAD

**Issue by xXxSoULMaNxXx** [ME3Explorer/ME3Explorer#445]
Windows 10 x64.  Legal.  NET framework  - better or same as one recommended.  

I open Texplorer and the top right part of the screen is not visible.  I cannot switch from ME3 to ME2 = I cannot build a tree = I cannot mod the game or use ME3Explorer.  

Please assist as I am counting on this to have a great first experience with ME2!

Thank you for your time and consideration.

**Comment by ghost** [comment]
1. This issue was reported in #392 and in prior isssues. Do not start new issues for the same problem, especially when they have been closed with an explanation.
2. This issue belong's in Kfreon's git issues, not here. See the Reporting Bugs page on the wiki.
3. Change your monitor scaling until you can see the button. Change it back once you've used the button.

**Comment by xXxSoULMaNxXx** [comment]
Hello.  

I play on a large 60' HD TV - will your suggestion work for that?

Also, the last post months ago said you would be working on it to some extent?  The problem would not continually be re-posted if ME3Explorer worked...

Thx

**Comment by ghost** [comment]
This will not be fixed until the tool is re-written. This issue belong's in Kfreon's repo not here. See the Reporting Bugs page on the wiki.
