### ISSUE TITLE
Accessing the same files from several tools

### ISSUE THREAD

**Issue by HeffU** [ME3Explorer/ME3Explorer#45]
Some of the operations in the toolset keep the file handle open, and we should probably take a look at this all over to ensure that nothing real weird happens if a user tries to open the same file in another tool. Most likely a stall/crash would happen, which is not too bad, but we could detect it and report it to the user rather than just stall.

**Comment by ghost** [comment]
Right now ME3Creator and InterpEditor are the only tools that get grumpy when you try to use the same file in them and other tools. For example, if you open the same file in those tools and it's currently open in Sequence Editor, when you try to re-enter Sequence Editor, you'll get an error and need to close the tool.

As a mod creator, I often need the same file open in several tools so I can fully visualize everything happening in the file  -- PCCEd2, Sequence Editor, Dialogue Editor, FXA Editor, Interp Editor and more. So, ideally, ME3Creator and Interp Editor some day get fixed to allow this. If there are limitations that prevent this, then, that's just how it is. Okay.

However, we really should have some mechanism in place for triggering a warning if the user tries to modify the same file in two tools. This has only bit me in the ass once, b/c I'm careful, but we should try to help modders out with a warning, if possible.

**Comment by SirCxyrtyx** [comment]
Wrapped most pcc file access in try/catch blocks. This should prevent crashing if another tool (ME3Creator) is hogging it.

@giftfish, can you explain what you mean about InterpEditor causing SequenceEditor to crash? Because, for me, it causes some graphical glitches in SequenceEditor when InterpEditor is opened for any file (no idea why), but dragging stuff around a bit in the SequenceEditor view seems to fix it. I'm not getting crashing though.

**Comment by ghost** [comment]
@SirCxyrtyx -- For me I get that graphic glitch with a big red "X" across the window where the sequence would be shown, but I also get this:

![simultaneoususe](https://cloud.githubusercontent.com/assets/13645804/12968157/def9a642-d022-11e5-9fdb-25b3cc768a5f.PNG)
