### ISSUE TITLE
.mod with nonstandard setup causes crashes/problems

### ISSUE THREAD

**Issue by HeffU** [ME3Explorer/ME3Explorer#46]
Possibly related to the .mod being both a mesh and texture mod.
In the following, go to files and use the "OPTIONAL FILES" -> "EDI AAP No Visor Patch" file:
http://www.nexusmods.com/masseffect3/mods/118/?

**Comment by HeffU** [comment]
What ends up happening is that modmaker tries to read one of the jobs as a texture job, due to it containing a reference to texplorer, and thus looks in the data for a texture to use as thumbnail. The data for that texture ends up being 
"0xA4ADF3BE|MASSEFFECT3.EXE_0xA4ADF3BE_visor.dds" + 2 bytes, so definitely not a texture, but I'm unfamiliar with this format.

Is it a mesh job format, or binary replace format, or just an old texture job format?

**Comment by starkgate** [comment]
Some testing with latest bugfix branch :
When repairing, ModMaker stalls. In VS, the following exceptions are given  :
A first chance exception of type 'System.NotSupportedException' occurred in PresentationCore.dll
A first chance exception of type 'System.IO.InvalidDataException' occurred in ResILWrapper.dll

When not repairing, ModMaker throws an error followed by a "Load cancelled".
![no_repair](https://cloud.githubusercontent.com/assets/12874678/9213397/26fd8f92-4092-11e5-8c3f-079fd37aa09c.PNG)

**Comment by KFreon** [comment]
Yeah that mod is super old. 
Unfortunately I don't have that DLC, so I can't really test it. 
It can be manually fixed, with more effort than ideal. For some reason, when it fails to update the mod, it doesn't show the failed mods anyway. It just shows half completed objects that break when clicked due to half their stuff being missing...

I'll look into it a bit more I guess.

**Comment by KFreon** [comment]
Can this be closed?

**Comment by starkgate** [comment]
![capture](https://cloud.githubusercontent.com/assets/12874678/13898848/42918ec0-eddf-11e5-8b7f-35e9aab72250.PNG)
This is what happens with rev743, it stalls in the updating of the mod. I'm not sure if it's worth it to get it working.
The log is quite interesting too, since it looks like it just stalls at the final step : http://pastebin.ca/3405469
I can see in the debug log that the revision the mod was built with is displayed. It would be nice to add that information to the 'Do you want to update' window, with a message like "If updating the mod runs into problems, try installing with 'detected rev' available at 'display sourceforge or nexus url' ".
e.g., this one was created with 628. 628 doesn't seem isn't available at Nexus, but 632 is, and seems close enough to work. The wording may require some changes for special cases like this one.

**Comment by KFreon** [comment]
We don't want to be recommending old revs to users. 
I don't think this is worth the effort of getting Autofix to fix it. 
It can be manually fixed if you really want.

**Comment by starkgate** [comment]
Well, either you recommend an older rev _for this specific use only_, or you deal with individual support for each of these old .mods every time a user wants to install one and can't figure out what goes wrong :/.

**Comment by KFreon** [comment]
I think supporting these old things individually would be easier.
Recommending revs is just a disaster waiting to happen. 
Feel free to point users to the debug log to see what rev a mod was built with though.
