### ISSUE TITLE
Issue with the Door_Console Texture

### ISSUE THREAD

**Issue by JunkoXan** [ME3Explorer/ME3Explorer#48]
Been installing the Texture Mod from Creep to test, and everything ran smoothly on installation until I came across the Door_Console Texture. once it hit that, it ceased TPF/DDS Tools. not sure on information that is needed, so, I did the debug window showing time as well my computer clock to show the time it was taking with the selection of the Door_Console with the information on the texture TPF/DDS Tools provided.

![bug](https://cloud.githubusercontent.com/assets/13722647/9157454/e40ebe4c-3ec3-11e5-88b3-d4f7b3519f30.jpg)

it shouldn't take close to an hour to install a 512x512 texture. :) I don't know if my memory serves me well at this point, but I think there may have been issues with this specific texture in the early revisions of ME3Ex, not sure exactly. I hope this helps.

**Comment by HeffU** [comment]
That does indeed look like some kind of crash happening in a background thread, I'll take a look at it when I get home from work.

**Comment by HeffU** [comment]
Turns out that this is a multitude of problems:
1: The original texture in the game files is bioware's own A8R8G8B8/L8 format, which seems to be L8 but with compression. (also possibly without the RGB channels)

2: TPFTools takes any format string with A8R8G8B8 in it and labels as ARGB. The modded file is an actual ARGB file, so TPFTools thinks the formats match and doesn't tell autofix to do anything.

3: Autofix would not be able to do anything about converting from ARGB to ARGB/L anyway, in its current form.

4: As TPFTools thinks that the formats are already correct, it send it to texplorer for installation.
Texplorer tries to read the modded file, which actually turns out to be a vriant of ARGB that is instead ABGR, and the internal DDS representation can't read this, and thus promptly throws an exception.

5: Texplorer gets the exception, and silently ignores it, promptly crashing that thread later on as the data is not in the expected format. This makes TPFTools wait forever for a background thread that has actually crashed, and no feedback is seen by the user.

**Comment by HeffU** [comment]
For now I'm electing to do a quick fix to nr 5, so that texplorer at least reports the fault and skips that texture.
For this particular modded texture I'm unsure if we can get it to the proper format expected in the .tfc, at least without writing our own converter.

**Comment by HeffU** [comment]
Turns out that for luminance maps we dont really care about the order of the channels, so I've managed to make this work anyway. Texplorer will still skip other formats it cant recognize though.

**Comment by starkgate** [comment]
I still get the stalling in the latest bugfix branch. I think the problem here is the Mips. The vanilla texture is 128x128 with 9 Mips, while the modded texture is 512x512 with 10 Mips. There is no MIPS flag though. I'd say MIPS detection still needs some work^^.
Other interesting information : when I go in Texplorer and try to extract this specific 0x75FE31AB texture, I can only see 8 sizes (aka Mips) to extract. The problem could then come from something else than Mips detection.

**Comment by HeffU** [comment]
This was working, but some other fix broke it again.
The problem now seems to be that autofix doesn't detect any difference between ARGB and ABGR, but when installing that format is unsupported so an exception is thrown.
I'll look into it later.

**Comment by HeffU** [comment]
Textures of type ABGR were being labeled as ARGB, which caused autofix to ignore them and texplorer to crash when installing. This should be fixed in a recent commit.
