### ISSUE TITLE
Abnormal time when deleting a file in TPF/DDS list

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#57]
Deleting a file from the "Delete Page" menu when having a lot of DDS' loaded, results in a very long wait (many minutes) compared to a small list of DDS' (a few seconds). I don't think this is normal, as the waiting time should be the same in both cases. It's as if TPF/DDS reloaded all DDS' before refreshing the list, which would be ridiculous.
This is not a new problem.

**Comment by KFreon** [comment]
Unfortunately, this is a limitation I ran into with WinForms and the way it has to ignore certain textures (i.e. texmod.def)
So unfortunately, it's not going to get fixed in this version.
The Delete Page is only for multiple deletions at once though right? You can still delete normally on the main page.

**Comment by starkgate** [comment]
Oh, really ? I never realized that I could^^.

**Comment by KFreon** [comment]
It's not really clear, especially since there's a Delete page :P
The only reason that page exists is because WinForms TreeViews can't have multiselecting without a lot of extra effort. 
From memory, that section is what prompted me to start writing stuff in WPF.
